### ISSUE TITLE
Store GitHub API tokens more securely

### ISSUE THREAD

**Issue by mkantor** [ptsochantaris/trailer#158]
I noticed that the API tokens are stored in plaintext in user defaults. It'd be nice if they were encrypted on disk, perhaps using [Keychain Services](https://developer.apple.com/library/mac/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html)?

**Comment by ptsochantaris** [comment]
That's good advice, I've had a chance to use this recently and it's awesome how simple it makes everything :+1:  However one part of building Trailer for me is to try and keep it clear of any pods, mostly to nudge me to investigate more aspects of Cocoa's API rather than simply relying on (the excellent and well tested functionality of) external pods.

Still thinking about this issue, and I still agree it's a good idea to keep the token better hidden, so stay tuned :)

**Comment by ptsochantaris** [comment]
Please follow the link to the issue above (#470) which contains a test build with this feature enabled. Will close this (erm... 9 year old 🤦) issue now. You're welcome! <64 ton weight, splat>
