### ISSUE TITLE
separate icon+menu for each server, or tabbed UI option.

### ISSUE THREAD

**Issue by dylang** [ptsochantaris/trailer#164]
### Problem

I am using two servers: `GitHub.com` and my company's `GitHub Enterprise`.

Currently we mix all pull requests from all servers.

This is overwhelming as my personal projects and my work projects have no relation.

It's also confusing when I'm at home and `Trailer` tells me it can't `Refresh` when I don't want it to refresh `GitHub Enterprise`, I only care about `Github.com`.

### Request

An option to enable one status bar icon+menu per server.

*or* 

An option to enable tabs in the dropdown.

*or*

I'm open to other ideas for splitting up the pull requests. :smiley:

**Comment by ptsochantaris** [comment]
Just thought I'd pass by and note that this is still on the TODO list, I haven't forgotten about it :)

**Comment by ptsochantaris** [comment]
Hi @dylang - I've just sent v1.3.5 out today with various tweaks and fixes, and was looking at this feature. I realise it's been a while since we discussed it last, but I realised there was a quick way to at least, for now, help you filter out PRs from server you are not interested in until there is graphical support for this, so I've added it in, and this link is basically just a tweaked version of 1.3.5 which contains this:

https://www.dropbox.com/s/hnbrrrmypdntpp0/Trailer-serverSearch.zip?dl=0

The way to use it is to type server:nameOfServer into the filter text field. It won't work with spaces (so "server:my server" won't work), and will match the name that you gave each server in settings, so if you have two servers: "githubPublic" and "githubEnterprise", all you would need to do it type "server:githubp" and it should show all the items from the publicServer. Note that you can still type filter terms after this, like "server:githubp trailer" to show all PRs or issues in this server with the word "trailer" in them.

I hope this helps a little for now, expect more news on the actual feature sooner rather than later.

**Comment by dylang** [comment]
Thanks @ptsochantaris I look forward to trying this!

**Comment by ptsochantaris** [comment]
Hi @dylang - It's been a while, so I don't know if you're even using Trailer by now, but in case you are, I've been working on adding properly separated menus based on API server.

After some thought I decided to go back to the original plan of having multiple menu-bar entires, and made a first test build here: https://www.dropbox.com/s/cgw8aj64qokzkzq/Trailer-API-Separation-Test-1.zip?dl=0

There are a lot of under-the-hood changes in this build, so it may not be the most stable ever. I'd therefore suggest you backup your Trailer settings and ~/Library/Application Support/com.housetrip.Trailer directory if you feel like giving it a test-drive.

If you do try it out, any feedback you have on improving this feature would be greatly appreciated!

**Comment by ptsochantaris** [comment]
Some fixes on sync error reporting and cleanups: https://www.dropbox.com/s/xwc45wyurus2um9/Trailer-API-Separation-Test-2.zip?dl=0

**Comment by ptsochantaris** [comment]
And some more fixes: https://www.dropbox.com/s/lt4jjvrxkni9m97/Trailer-API-Separation-Test-3.zip?dl=0

**Comment by ptsochantaris** [comment]
Getting there: https://www.dropbox.com/s/dbg1mstlyrcv9qe/trailer-140-rc4.zip?dl=0

**Comment by ptsochantaris** [comment]
Update: https://www.dropbox.com/s/51qmlo3hzmgo49w/trailer-140-rc5.zip?dl=0

**Comment by ptsochantaris** [comment]
Update: https://www.dropbox.com/s/0vy182l44qy4qyi/trailer-140-rc7.zip?dl=0

**Comment by ptsochantaris** [comment]
Update: https://www.dropbox.com/s/6vo013rt86h3imt/trailer-140-rc8.zip?dl=0

**Comment by ptsochantaris** [comment]
Update: https://www.dropbox.com/s/fvilf3yeovx1xni/trailer-140-rc9.zip?dl=0

**Comment by ptsochantaris** [comment]
Version 1.4.0 is up now, and contains this feature. Please feel free to open a new issue if you have further thoughts and/or suggestions for Trailer.
