### ISSUE TITLE
move pull requests that mention a team that I am a part of into "participated"

### ISSUE THREAD

**Issue by akalman** [ptsochantaris/trailer#172]

**Comment by ptsochantaris** [comment]
Sorry for the really late reply - this month has been too busy.

I think there was a feature request like this a while ago, and I was happy to add that feature as it sounded pretty simple - I even investigated the API for reading teams which was pretty simple.

I'm still more than happy to look into adding this but can you give me more info on how the team participation is handled in mentions, i.e. what the formatting is like? I think that's where the previous discussion had stalled :)

Sorry for being a bit vague - if you can provide a little more info (as team mentions is oddly something I am not familiar with) I'd be more than happy to resurrect this feature and add it.

**Comment by akalman** [comment]
well as far as I know, teams are only available within the context of an organization.  but, for example, if github had a team for its boxen product, it could feasibly be meantioned using `@github/boxen` where `github` is the name of the organization and `boxen` is the name of the team.

**Comment by ptsochantaris** [comment]
This should be quite straightforward to support, apart from that is there another way to reference a team?

**Comment by akalman** [comment]
not that I am aware of.

https://github.com/blog/1121-introducing-team-mentions

**Comment by ptsochantaris** [comment]
Aha, thanks for the link - sorry for the (ultra) late replies but it's been a crazy couple of months. Will check it out and add it in :+1:

**Comment by akalman** [comment]
thanks!

**Comment by akalman** [comment]
To potentially save you some time there is a github endpoint specifically for the authenticated users' teams at `/user/teams`

**Comment by ptsochantaris** [comment]
Hi @akalman,

I think I’ve got the first implementation of this feature, but since I’m not heavily involved with team mentions, I’d like your help in verifying that it’s properly implemented :)

NOTE: Due to possible DB migration issues, please ensure you back up your Github token so you can restore it in case it gets lost! Otherwise reverting to the previous version of Trailer from this will wipe it. (chances are you probably won't need to, but let's play it safe :))

You can use the build below and turn on "Move PRs that mention my teams to ‘Participated’” from the Comments section in preferences. After that, PRs which contain an @org/team reference should show up in your participated list after a refresh.

(One known issue which is on my list is that this uses dumb string matching at the moment, so @org/team1 and @org/team12 will both match if you belong to the first one. I'll fix this for the actual release by using regex, but first I wanted to see if anything else was wrong with the logic)

If you get a chance to try it out, let me know of any weirdness of problems you may encounter!

https://www.dropbox.com/s/b02w2cw66s5br6v/Trailer-auto-participate-team-mentions.zip?dl=0

**Comment by ptsochantaris** [comment]
Ah, another minor issue - (for now at least) you need to have "move PRs that mention me to participated" on as well for the above to work.

**Comment by ptsochantaris** [comment]
Ok, so, ignore the previous comment, there were other errors there too, so here's a fixed build which won't require both to be on in any case:

https://www.dropbox.com/s/gxixehws5viwrfv/Trailer-team-participation.zip?dl=0

**Comment by akalman** [comment]
sure, trying it out now.  Here are some quick test cases I'm planning on going through eventually, I'll check them off and add more as needed

- [ ] creating a PR with a team in the description adds to participated
- [ ] creating a comment with a team adds to participated
- [ ] enabling the option adds all previously created PRs that qualify to participated
- [ ] creating a PR with a team that I am not a part of in the description does not add to participated

**Comment by ptsochantaris** [comment]
Nice, and very thorough! Let me know how it goes.

Bear in mind that in some cases things may only update after a refresh (mental note to self: They don't technically need a refresh, PRs should be re-processed after the option is ticked like in other options, I'll be sure to fix that)

**Comment by akalman** [comment]
looks good. :shipit:

**Comment by ptsochantaris** [comment]
Great news! Thanks for testing it out. Also, looks like the mental note above wasn't needed after all, I had actually done it properly in the first place too :)

The build above should work fine BTW (may use slightly more memory as it is as debug build, but the difference should be small) so feel free to keep using it until the next update goes out, but please DO keep a backup of your tokens as the DB migration will break when you upgrade to it from this build, as the DB schema will probably morph a bit more until then.

**Comment by ptsochantaris** [comment]
Doing incremental test build for the next release here: https://github.com/ptsochantaris/trailer/pull/185 They should all contain this feature. Feel free to test any of them, or if you prefer to play it safe, stick with the one from here, which is guaranteed to be stable :)

**Comment by ptsochantaris** [comment]
Version 1.3.0 is now live and includes this fix, so I will close this, but please feel free to re-open in case there are further problems problems, or feel free to open a new issue.

Thanks again for the suggestion and the thorough testing you put into this feature!

You can upgrade your version either from here: http://ptsochantaris.github.io/trailer/trailer130.zip or more easily from About -> Check for updates
