### ISSUE TITLE
Ability to disable all comment notifications

### ISSUE THREAD

**Issue by danielschwartz** [ptsochantaris/trailer#180]
It would be great to simply turn off all comment notifications. As of right now, it seems like you can only specific certain username to ignore comment notifications from. Our team (luckily) comments a ton on each others pull requests, so getting bombarded with notifications isn't really helpful (but the badge is helpful).

**Comment by ptsochantaris** [comment]
Makes sense and its an easy tweak - Will add.

**Comment by brianmuse** [comment]
Thought I'd chime in here vs. opening another ticket. In the same vein, the persistent notifications can really stack up after a long period of time, and then it becomes a long process of dismissing them all one at a time. Would it be possible to make these notifications expire after a period of time?

**Comment by mcos** [comment]
I would like to echo @brianmuse here. Love the app, but having the notifications expire (I think they used to do that) would be really helpful.

**Comment by pedrocunha** [comment]
I +1 the disable all notifications BUT i think it would be even more awesome if we could control per repo or per PR.. somehow. I think bonus points if we could act on the "subscribe" button which is generally present in PR UI via the GH api. 

> Sticky notifications

I think this default behaviour changed in the port to Swift.

**Comment by ptsochantaris** [comment]
Thanks for chiming in guys!

@brianmuse Much faster to swipe-open notification center and use the "x" button to dismiss all of them at once from Trailer's section.

@mcos You can make notifications be temporary by changing them to "banners" from preferences -> notifications, although I think that is then too fast. There was no logic to actually expire notifications before, although after a certain amount of notifications OS X will expire them anyway.

@pedrocunha I think that used to be the default before, I haven't touched the setting, not sure why a lot of people are seeing this as a new behaviour - something Swift-related, perhaps, and before OS X was ignoring it. I've got a feeling this is not what most people want though, so I may change the default back to banners. Interesting thought on per-repo setting, will keep it in mind!

**Comment by ptsochantaris** [comment]
Here's a build with this option (it's in preferences -> comments) It's the simple form, just a global switch, of course.

The thing about @pedrocunha 's suggestion is that it also brings in a ton of stuff that I would also like to have per-repo, which means a big reworking of the repos list. In my mind this is part of a larger feature, which is to make a lot of settings per-repo.

Have a go and let me know if it works the way it should (didn't have a lot of time to test this as it's been a hectic day, so I thought, why not make the requesters do it AND give them a feature faster too :-P )

https://www.dropbox.com/s/36jcxhqm4q3ikvl/Trailer-DisableAllComments.zip?dl=0

**Comment by pedrocunha** [comment]
This is just food for thought but I think disabling comments completely (I know its an option and everyone is free to toggle it on/off) kinda defeats a bit what Trailer wants to achieve. Sometimes I personally like the fact i get one notification because I know someone just started to review my PR but if you have a couple of people or just a lot of comments, notifications might be too noisy or distracting. 

So what if we could buffer notifications for PRs? i.e. let's stay that Trailer buffers notifications and if it gets more than X amount of comments for PR Y within a couple of minutes it just keeps agregatting, and when off that period presents a single message saying you have W comments in PR Y ?

**Comment by ptsochantaris** [comment]
@pedrocunha I'm probably being a bit mentally hubristic here :) but I would say that what you are describing is exactly what @danielschwartz is trying to achieve in the first place by turning all comment notifications off - Viewing it from the perspective of your idea, in an environment where there are a ton of comment notifications, the Trailer menu becomes the "collapsed" pr notification list that you describe.

Gathering a lot of comments and issuing a notification is a thought, but then where would you draw the line? It becomes tempting for the user to set the "gathering" time threshold high, and then Trailer is useless to them, because other devs are shouting "didn't you see my comment?" in the chat by the time they have been notified anyway. In fact, the most busy the PR the less likely is that the user will find out that way.

Of course, this doesn't address the "one solitary comment" part of your idea which certainly has merit (i.e. "disable all comment notifications, but notify in case an "idle" PR gets a comment) - but would that be useful enough for you to warrant creating a feature request? If so, let's go for it! -- But for the purpose of this specific issue thread, I think the basic "mute all" option (or ideally, like you said, per-repo, which is a bit hard at this point) is the way to go.

**Comment by ptsochantaris** [comment]
Incidentally, I just found out why the notifications default was not followed before - the app wasn't code signed, and now it is :)

Have reverted the setting back to banners, as it seems most users prefer that, and there is the notification center anyway for history.

**Comment by mcos** [comment]
Thanks @ptsochantaris! Love the work you're doing!

**Comment by ptsochantaris** [comment]
Hi, version 1.2.1 is up, which includes this feature. Will close this issue for now, but please feel free to re-open if you encounter any issues with it.

**Comment by danielschwartz** [comment]
You guys rock, we really appreciate this.

**Comment by aditigupta96** [comment]
Hi, I am looking for this feature to turn off the comment notification for all watchers. Where can I find it?

**Comment by rsumner31** [comment]
~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
