### ISSUE TITLE
Unable to toggle console logging

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#187]
When using Trailer 1.3.0, I'm unable to toggle the console log if enabled. Once enabled, it's not possible to disable it. Here is a screencast that captures the continuous loop (where check state is not toggled properly):

![console_log_toggle](https://cloud.githubusercontent.com/assets/50245/6994296/5dbe856c-dad1-11e4-83f8-77980ba142c4.gif)

**Comment by ptsochantaris** [comment]
Thanks for calling it in, I should have put better feedback there -- In fact logging is always locked to "on" for debug builds - the settings panel should let you know about that. I'll add a little code to output the right message there in the next test build (will most probably post one tonight)

**Comment by bkuhlmann** [comment]
oh, ok, that makes sense. What about not improving the message by disabling the ability to toggle the checkbox when in debug mode? The one could visibly see that the checkbox is locked to being always on? A short text description (in red maybe) that said "Locked for development versions" could be really helpful.

**Comment by ptsochantaris** [comment]
Well, like you say, if the control is disabled then an explanation is needed, and in that case we've got extra UI to babysit. In this case, since it's a bit of a corner case it's just cleaner to show a message when the user selects the checkbox and save some precious pref panel real estate :) I do prefer your "development versions" to my "debug builds" in th message though, will replace it.

**Comment by bkuhlmann** [comment]
Good point, regarding screen real-estate. Sounds good. :smile:

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this for now, but please feel free to re-open in case you'd like to add to this for any reason.
