### ISSUE TITLE
OSX Dark Mode support is broken?

### ISSUE THREAD

**Issue by StarkMike** [ptsochantaris/trailer#191]
Just updated to 1.3.0 and it seems to not support my dark mode settings anymore - was fine before the update.

**Comment by ptsochantaris** [comment]
Hi, and thanks for reporting this -- however I can't seem to reproduce it, dark mode seems to be working fine here.

- Before I ask around to see if anyone else is getting this, can you give me some more info which can help me locate the trouble?
- Can you try disabling and re-enabling vibrancy support in Trailer's preferences just in case this is a stuck setting for some weird reason?
- What happens if you turn dark mode on and off in system preferences?
- Does vibrancy work in non-dark mode?
- Also, if you don't mind me asking, what are your system's specs?
- Can you provide a screenshot of what the app looks like on your system in dark mode?

Sorry for all the questions, but this is puzzling me and I'm trying to think of ways we can investigate it more :)

**Comment by StarkMike** [comment]
Thanks for the response.  Posting here in case others get this issue.

Turning off Dark mode and back on (in system preferences) seems to solve the issue 
(I had attempted the vibrancy support idea in Trailer before with no results, which prompted me to post).

**Comment by StarkMike** [comment]
Keep up the great work!!

**Comment by ptsochantaris** [comment]
Aha, glad this fixed it, and thanks!

Still, a bit worrying that this trick was needed in the first place though, I'll double-check if the initialisation sequence picks up the system's dark mode setting correctly.

If you do notice this breaking consistently in some way, for instance if Trailer launches in the "wrong" vibrancy mode, please do open a new issue!

**Comment by cgatesman** [comment]
I see this issue occasionally after rebooting.  After all logged in, trailer is stuck in Light Mode even though my OS X (El Capitan) is in Dark Theme.

<img width="531" alt="screen shot 2016-06-15 at 12 13 46 pm" src="https://cloud.githubusercontent.com/assets/6276072/16087875/ac62944a-32f2-11e6-850f-e203975a0369.png">

Restarting trailer does not fix it.  However if I quit Trailer and start it back up later in the day, it seems to come back to dark.  I haven't been able to figure out what triggers it either way.

**Comment by cgatesman** [comment]
Interesting.  I just turned off Dark Theme in OSX, and trailer switched to Dark!

<img width="519" alt="screen shot 2016-06-15 at 12 17 31 pm" src="https://cloud.githubusercontent.com/assets/6276072/16088028/37a0c996-32f3-11e6-9847-df387afe15f1.png">

**Comment by NiXXeD** [comment]
I continue to have this issue sporadically. It always stays in light mode when I turn the computer on. For a long time, if I closed/opened trailer, it would fix and be in dark theme. Now, I cannot get it to switch to dark theme at all any more. Several other coworkers experience the same issue.

**Comment by ptsochantaris** [comment]
Hi, sorry for the late response but this issue was closed so I didn't see the new comments here.

We're looking at this regression on the latest beta (or I ought to say, RC by now) on this issue: #294 and it may be corrected now. Can you have a go with the latest beta to see if it improves things? (You can download it from #289)

If possible, please post comments and feedback on that issue as I may miss comments on this closed one.
