### ISSUE TITLE
Move assigned items to "Participating"

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#196]
It would be nice to be able to see assigned items in the "Participating" section. Currently they show up in the "All" section unless I have enabled "Move assigned items to My section". I'm using Trailer 1.3.1.

**Comment by ptsochantaris** [comment]
I see what you mean - it actually makes a lot of sense, especially when combined with the "hide all" option. It can replace the "move assigned items to My section" checkbox with a dropbox:

Assigned items: [Move to Mine / Move to Participated / Don't Move]

The middle option is most probably the sanest default, but some people may still want to be able to ignore assigned PRs for whatever reason, so it's good to have the three options I think.

What do you think about this as a solution?

**Comment by bsiegel** [comment]
That sounds perfect, and I agree that 'Move to Participated' makes the most sense as the default. Thanks for considering this, and for making a fantastic tool!

**Comment by bsiegel** [comment]
Incidentally, if this is implemented it would probably also make sense to have an option in History > When Something is Merged/Closed >  "Keep App / Keep Mine & Participating / Keep Mine / Don't Keep".

**Comment by ptsochantaris** [comment]
It does make sense :+1: May be slightly tricky due to the simple index<->option mapping currently used in settings for this, but that's an implementation detail really.

**Comment by ptsochantaris** [comment]
Hi @bsiegel!

I've been cooking the stuff we discussed and have a debug build with these new features.

It *seems* to be doing the right thing, but because that involved refactoring some logic I'd rather put more eyes on it than just mine for the next few days :) Especially if you deal with a high volume of externally assigned PRs and/or issues, I'm sure you will be able to spot something that may have gone wrong.

Things to watch out for:
- The new features we discussed not working as they should, obviously
- Look out for any weirdness in notifications, perhaps not seeing some notifications that you were expecting to see, or the opposite
- In case you'd like to downgrade to a previous version, you can, there shouldn't be any DB problems, but note that the upgrade will have reset your previous settings (those related to the new features only) back to defaults, so you may have to set those again.

If you get the chance, give this a go and let me know of any problems you may encounter.

https://www.dropbox.com/s/o9db832fkjosx9y/Trailer-assign-merge-and-close-handling-policy.zip?dl=0

**Comment by ptsochantaris** [comment]
And a small update already :)

https://www.dropbox.com/s/vmu64g2ibi4xzyy/Trailer-assign-merge-and-close-handling-policy-2.zip?dl=0

**Comment by bsiegel** [comment]
Awesome, thanks! I am testing it now and will let you know how things go. Initially at least everything seems to be working as expected.

**Comment by ptsochantaris** [comment]
That's encouraging :) Take your time with it, there's no hurry :+1:

**Comment by bsiegel** [comment]
Still humming along, have tried running with both "Move to My" and "Move to Participating" options for multiple days each and PRs are appearing as expected. :shipit:

**Comment by ptsochantaris** [comment]
Fantastic :+1: thanks so much for helping test this. If you feel like taking a bigger risk, there's a more updated build here which includes more changes to repository PR/Issue visibility, building on top of changes made here: https://github.com/ptsochantaris/trailer/issues/189

Absolutely no problem if you don't feel like risking your workflow on a potentially buggy build though!

Thanks again for testing, looking forward to releasing the next update soon!

**Comment by bsiegel** [comment]
I'll give the new build a try tomorrow, thanks for all your efforts!

**Comment by ptsochantaris** [comment]
No problem, thanks for helping improve Trailer! Keep the suggestions and bug reports coming :+1:

**Comment by ptsochantaris** [comment]
Just noting here are well that the latest update (1.3.4) is now live, and includes the fix for this issue. Will close this for now but please feel free to reopen or post a new issue in case you encounter any problem. Thanks again for the suggestion, I hope it makes your life easier!
