### ISSUE TITLE
Question: Issues only assigned to me?

### ISSUE THREAD

**Issue by jules2689** [ptsochantaris/trailer#212]
Is there a way for the Issues menu to *only* show the issues assigned to me. This would be the same as the URL https://github.com/issues/assigned

Wasn't sure if this was possible, and didn't see any docs.

**Comment by ptsochantaris** [comment]
Hi @jules2689 

If I understand you correctly, you should be able to do this using a combination of two things:

1) You can limit which sections are visible for any repo from the "repositories" tab in preferences. You can pick, per repo, and separately for issues and/or PRs:

- Hide: Hides all items from this repo.
- Mine: Shows only items from a repo what would end up in "my" section.
- Participated: Shows only items from a repo that would end up in "my" or "participated" sections. This is what I would recommend you set, as you can take advantage of automatically promoting certain items based on assignment, whether you are mentioned and so on, etc, based on the options below.
- All: The default, shows items is all sections.

2) The other options you probably want to look into are the two "Move items mentioning me/my teams to Participated" (in Comments) and also "When an item in 'all' is assigned to me, move to..." (in Display) - either set it to "my" or "participated", depending on your preference.

Turning these options on and setting the repo options to "Participated" for the repositories whose issues you want to limit will give you what you want.

I hope this helps, let me know in case I have misunderstood your question.

**Comment by ptsochantaris** [comment]
PS In fact, to mimic the "assigned" list exactly you wouldn't activate all the options in (2), just set repos to show "Mine" sections only and set "when an item in 'all' is assigned to me" to "Move to 'my' section". (However, configuring it like I said above could actually prove to be more useful IMHO, but whatever works for you is best of course)

**Comment by jules2689** [comment]
Yea, that almost gets it :)
The problem that remains is that this includes all issues I have created. At the moment, I have well over 40 created issues across various repos, but I do not want to track them all. I only want to track issues specifically assigned to me. Otherwise it becomes overwhelming if you are a part of a larger organization :( 

If this is not possible, I would be more than happy to take a look through the code to help make this happen!

**Comment by ptsochantaris** [comment]
Ah, I see! Interesting corner case then :)

Yes, at the moment it's not possible to hide items created by you. It should be easy to add as an option in the next update, but if you're feeling adventurous feel free to tweak the queries in "requestForItemsOfType" in ListableItem.swift and hardcode it in!

What you probably need to add is:
        andPredicates.append(NSPredicate(format: "userLogin != 'jules2689'"))

around line 382 in ListableItem.swift, and you should be set.

For making this permanent, what would you think of a checkbox in Display saying "Hide items created by me" as an option? Or do you think there is a more elegant way to handle this?

**Comment by jules2689** [comment]
That would be an easy addition. That said, I would be a little concerned with adding a checkbox like that. I feel like it could get out of hand with everyone's edge cases. Give ma a little bit of time and I'll see what I can do to make a nice elegant solution. :)

Side note: Would it be possible to add a wiki that outlines the different sections of the Preferences with a more in depth example of what it does (with image examples). This could be more long term, but it would definitely help figuring out a nice set of settings people may want.

Alternatively, have you noticed "profiles" of different people? What I mean, have you noticed patterns of what people what - for example, I want only my issues, my PRs and PRs that I am mentioned in. Another person may want all issues in this repo, but not that one etc.

**Comment by ptsochantaris** [comment]
Yes, I am indeed concerned with feature creep in the options, but IMHO the best way to handle this is to progressively/naively add options as required, identify patterns as they emerge, and then "collapse" sets of options into a new option, or structure. For instance the "when an item is assigned to me" option used to be 2 checkboxes that would have become three. In this case, they got collapsed.

That said, I'm certainly more than happy for suggestions and/or code that improves any of the above, please do let me know your thoughts!

Regarding docs, I would much rather add some help text, and annotation popups on the preferences pane rather than create separate documentation TBH. But I definitely get that it's past the time where the preferences were simple enough to be self-explanatory, a few "?" buttons here and there would probably be a good idea :) Like you said, it's more a long-term thing, but it's definitely a good point.

**Comment by jules2689** [comment]
I'll try to think of something. I think the biggest issue is that it does not follow the same structure as the menu bar icons or github.

We have Pull Request and Issues, but there are no settings areas for those. Instead the preferences are split up between multiple tabs. If you're okay with letting me think about this for a while, I may attempt a consolidation to try and explain the settings a bit more. I'm new to Trailer, but I think this will be an asset. If a newbie can figure out settings, then I'm sure anyone else can :) One of those "new eyes" mentalities.

I think this is a great asset for developers and I intend to continue to use it. Thanks for being open to discussing this and contributing to the open source community!

**Comment by ptsochantaris** [comment]
New-eye mentality is priceless, looking forward to hearing and discussing your suggestions :+1:

Issue support in Trailer is very new, the prefs were mostly about PRs, and when adding issues basically I just moved every option from "do X for PRs" to "do X for an item" which, you're right, doesn't make intuitive sense to a new user.

Issues were originally meant as an extra to PR management, but I think they are important enough that new users may want to use Trailer just for that, and then it gets weird, because there are different needs for issues than for PRs.

However, like you said, I'm not sure how to "split" settings without simply doubling them and/or making them annoyingly complicated :)

Finally, remember that changes have to be incremental enough to cater for migrating previous settings and not over-complicate the iOS interface too. I'd definitely recommend thinking this in "phases" rather a big re-imagination of settings (or you can prove me wrong and come up with something awesome :))

But the bottom line is, preferences are not great, they DO need to improve, so I'm absolutely open to suggestions!

**Comment by jules2689** [comment]
Can you assign this to me? Is that possible without being a collab? Will remind me then, haha

**Comment by ptsochantaris** [comment]
It doesn't seem to be assignable ATM, sorry! But this is your issue, so it should be in your "mine" list already, shouldn't it?

**Comment by jules2689** [comment]
I'm not watching this repo at the moment for notifications reasons, that said, even if I did it would be amongst about 50 other issues :P

**Comment by ptsochantaris** [comment]
You can add the repo, and set "none" PR and "Mine" for issues. That should simply add this issue for you.

**Comment by jules2689** [comment]
Here is a writeup I did. Let me know what you think.
https://docs.google.com/document/d/1dTjqDJ5X0s57TqDyouF7WwJ3nIsDAXgcBtLJjCb_OHk/edit?usp=sharing

**Comment by ptsochantaris** [comment]
Just had a quick glance, nice! :+1: Going to set aside some time to go through it properly, so I can do it justice, and provide thoughtful feedback in the next couple of days. Great stuff!

**Comment by ptsochantaris** [comment]
(Hi, just a quick note to let you know I haven't forgotten about looking into this, it's on the TODO list, I'm just overloaded with work these weeks so I may be a little while longer)

**Comment by jules2689** [comment]
Oh, no problems at all :) Thanks for the update! Took me a few weeks to sit down and find enough time to write it, so I totally understand timings!

**Comment by ptsochantaris** [comment]
Hi, another note to keep you up to date - Trailer work has been lagging a bit due to a heavy project workload these days, and what time I had went into iOS9 OS feature support and cleaning up the code base a bit. Since it's been a while, i just wanted you to know that going through your feedback is still high on my TODO list, it's just the TODO list hasn't moved much recently. Do stay tuned, I definitely haven't forgotten about this :+1:

**Comment by jules2689** [comment]
Thanks for the update :)

**Comment by ptsochantaris** [comment]
Hi, I have finally found some time to get around to your excellent writeup! Thank you once again for your patience, Summer and Fall are always very busy periods for my work.

So, going through some of the points:
- Totally agree "Repositories" should be something else. It used to be the same, but not anymore. I'm wondering if "Synchronisation" is the right name or "Watchlist" would be clearer, to make it super-explicit that this is the aspect of Github it reflects? What do you think?
- While I understand your point about making sections match Github 1:1 in terms of semantics (i.e. section for "authored" another one for "assigned" etc. instead of mapping them to Trailer's own section format) I think that it's one of the big reasons some use Trailer - i.e. that it abstracts all this into "need to care" or "FYI" sections :) creating a more workflow-oriented display rather than a status-oriented database-like display that Github provides.
- *Comment badges & alerts for items in “all”* - very true, this title sucks and was originally there to help the option fit better into the tiny one-panel options Trailer used to have. This needs to change :+1: 
- *Open items at first unread comment* Yes, it means exactly that. But it sounds like this section (and various options) could benefit from tooltips (I've done something similar for the iOS version, with extended descriptions under each option)

On your comments in "History"
- Totally agree with your criticism of the word "Keep" - it should be "Move to 'Merged/Closed' Section", definitely.
- "Don't keep items merged by me" is tricky, as it makes perfect sense if you think about it, but it ought to be rephrased, you're right: "Always discard PRs merged by my, regardless" (i.e. doesn't matter what the setting about merged items, throw away things I merged) Also, it should be grayed-out if the "merged" dropdown above is set to "Don't keep" (or whatever it ends up being called)

Display
- Creation time: Yes, phrasing is a bit weird here. Will think more about this.
- Count of items: This option used to be the old default of Trailer, showing all open PRs instead of what was filtered-for. This was long before filtering, predicates, and Repo PR/Issue visibility settings, hence the default was changed to "off" It's there as some users want to see the total count of PRs/Issues across all synced Repos no matter what their local filters show. For instance, when checking overall company "buffer status" for code review.
- Use vibrancy turns on Vibrancy support in OSX, i.e. translucent menu support, night mode support, etc. Probably needs to be "Use OSX Display Vibrancy if supported" :)
- "When an item in 'all' is assigned" - Yes, "all items" refers to the big "rest of items" section. Probably needs to be "When something from 'all items' is assigned to me"?

On status/labels:
- "make status items always selectable" - yep, definitely a phrasing issue there. Most probably "Make any displayed PR status lines always selectable"
- Good point on the scope - that ought to read "Show notifications for new/updated statuses of visible items" I think? Thoughts?

About having separate PR/Issue sections:
This does make sense, in a very obvious way, and I definitely won't argue against it. But again it's one of those very deep changes that I would be scared to make "lightly", since it's not really an "options" issue, but a change in how items are handled and treated, depending on their type.

Doesn't mean it shouldn't happen, in fact you're dead right both about how this can confuse a new user as well as how people will end up having varying requirements for Issues and PRs.

Like the other items relating to tech debt I mentioned above, I just wouldn't prioritise it for now, especially since PR/Issue support is "new" and the code has yet to "settle" properly and treat both types as properly distinct entities. It is improving though, so this may happen sooner rather than later. The Repo handling policies was a big step in this direction, though, so eventually this "ball of twine" will unravel :)

On the Proposal section:
- To sum up, first off, many thanks again for your detailed write-up. Your perspective has been invaluable. I don't think there is one place where you are wrong or I would disagree. Anything that I wouldn't include in the advice taken would have to do with labelling and clarity of the setting concerned, and the rest would be out of simple practicality issues (i.e. time available and keeping code-churn small between releases rather than big sweeping changes)
- Once again I get your point in making the terminology more aligned to Github, but I think the confusion is actually caused because the terminology RESEMBLES Github. Trailer is trying to help you out by "detaching" the items from such statuses, and letting you organise them in an "inbox-manner". How about perhaps using totally different terms, so they don't get confused with Github's?
- Combining Display and Sorting is a slum-dunk :) Totally obvious, easy, and should have been done already, no idea why I hadn't thought of that.

I'm going to make a second pass at this in a bit, but I already have some good notes on some immediate quick-wins for improving settings based on this:
- Info tooltips on all settings
- Combine Sorting into Display section in OSX
- Rename certain items for clarity as discussed above

Will think more about the PR/Issues settings divide which you quite rightly address, and how we can make this happen...

**Comment by jules2689** [comment]
No problems. Its always super busy as a developer (writing this is my 10 minute break from my hair pulling experience with Xcode).

This is definitely a multi-step process to make over time.
> Info tooltips on all settings
> Combine Sorting into Display section in OSX
> Rename certain items for clarity as discussed above

---

> Totally agree "Repositories" should be something else. It used to be the same, but not anymore. I'm wondering if "Synchronisation" is the right name or "Watchlist" would be clearer, to make it super-explicit that this is the aspect of Github it reflects? What do you think?

I like Watchlist. That is what you are really doing here.

> "When an item in 'all' is assigned" - Yes, "all items" refers to the big "rest of items" section. Probably needs to be "When something from 'all items' is assigned to me"?

That makes sense to me

> Good point on the scope - that ought to read "Show notifications for new/updated statuses of visible items" I think? Thoughts?

Have to look at what I meant here again, but I think it makes sense



These are great first steps and I agree with the things you said above as well (all your questions). The Repo/Issue thing is something I was a little iffy on proposing because it is such a big change. Perhaps it would make more sense to start with these actionables and then reconsider?

Thanks!

**Comment by jules2689** [comment]
Just got the update :)
Things are definitely a lot more clear. I haven't gotten a chance to go through it properly yet, but it it definitely a vast improvement.

**Comment by ptsochantaris** [comment]
Ah, crap, I completely forgot to ping you about that release here, I'm so sorry! I meant to do that and also mention your valuable input in the release notes right afterwards, and then I seem to have been swallowed up by other work. Fixed!

Really glad you see an improvement! :+1: 

Like we talked above, this is a first round really, there should be a more radical re-organization of options, to allow issue-specific and pr-specific settings, or, compounding this even further, making a setting local to a repo too. So that you can target behaviour for PRs from a specific repo, for instance, Issues for another repo, global settings for everything etc.

(You can already see how in the watchlist tab options are starting to become a bit kludgy - it's not going to work adding columns for every new per-repo setting :))

The way I had tackled this in the past for an old app I had made called ReFaMo, was to approach settings in a particular way:

- A section of app-specific settings, like using Vibrancy, for instance, exporting, keyboard, etc
- Every data-item-specific setting was then grouped into a "configuration layer" if I can call it that for purposes of discussion here. There as a global layer, and hierarchical "inheritance" layers going down from that. For instance, in Trailer, it would be something like:
```
Global
|
|-- Server 1
|    |
|    |-- Repo1
|         |--PRs
|         |--Issues
|    
|-- Server 2
|    |-- Repo2
|         |--PRs
|         |--Issues
|    
...
```

Each layer could have a setting set to a value, or set to "inherited". The Global layer settings cannot be "inherited", i.e. they need to have a value (or blank, or whatever their default is :)).

This means that you can go and set specific behaviours for entities of a specific type, intervening only where you would prefer, while leaving all other settings to "inherit" from the global ones.

It worked well, but in the case of that older app it was easier because all the settings were visible in one "tab", and the tree was the actual hierarchy being edited - but in the case of Trailer, there are too many options to include in one view, so it may get tricky.

This is just brainstorming for now, but I was thinking perhaps "breaking" settings into two.

The first one is the app-wide settings, like "preferences". The second is the "behaviour" window, which has the watchlist on the left, like the above tree. The root is "All" or "Global" or something.

Selecting a repo (or PRs/Issues/etc under it) defines the context for the panel on the right, perhaps with a stronger title on top to make sure it is clear the user is editing a specific context.

That panel then only edits that context. So, for instance, option "move assigned PRs to X" is by default "Inherited" i.e. what it's set to in the parent (for instance, in the repo layer, or if we're editing the repo layer, the server layer, or if we're editing the server layer, the global layer)

I am thinking that this approach fuses the servers/watchlist and all their settings in one go, BUT this is not an easy change, it will break things badly :)

However, something will need to be done sometime. What do you think of this as an approach? Would it be perhaps too confusing or too "over-engineering-y"?

Does my description make some sense? Hope I haven't confused you.

**Comment by ptsochantaris** [comment]
Hi, just to keep this list tidy, and since the conversation has moved a bit from the original issue, I'm going to close this. I'll be more than happy to continue discussing this on its own issue if you still feel like it in the future. Just open a new one and we can revisit this whenever you feel like it 👍
