### ISSUE TITLE
glitch on avatars

### ISSUE THREAD

**Issue by Karlotcha** [ptsochantaris/trailer#213]
I am on version 1.3.5 on OS X 10.9.5 and the avatars are all glitchy when I scroll :( 

For example:
<img width="52" alt="screen shot 2015-07-06 at 11 58 47" src="https://cloud.githubusercontent.com/assets/1086288/8520885/6a6f91f4-23d6-11e5-871f-0ae2a4eb59e6.png">

Or:
<img width="56" alt="screen shot 2015-07-06 at 11 58 19" src="https://cloud.githubusercontent.com/assets/1086288/8520886/6c452a02-23d6-11e5-9c36-7d5869167273.png">

**Comment by ptsochantaris** [comment]
Hi @Karlotcha - I see the usual bug that plagues you is back. Ugh :(

It's most probably because I have re-enabled layer support in avatars and that weird GPU bug in 10.9 has reared it's ugly head once again. I'm going to send you a build in a little bit which has an option to turn that layer support off, which hopefully should fix your issue. This may make the avatars a little less attractive, however.

I would strongly urge you to upgrade to Yosemite soon, as 10.9 support will most probably be dropped when 10.11 comes out in the fall, plus it should no longer have the issue you are experiencing now.

**Comment by ptsochantaris** [comment]
Hi @Karlotcha 

Sorry for the delay in getting back to you. Try this update - it ought to fix your issue. Thankfully no special option should be needed. It's a debug build, but if all is well I'll push out a release update in a little bit.

Let me know if this improves things for you:

https://www.dropbox.com/s/g0rd6nhnawbh5l1/Trailer-avatar-test.zip?dl=0

**Comment by Karlotcha** [comment]
Hi @ptsochantaris 

Thanks, this fixed it! :)

**Comment by ptsochantaris** [comment]
Great news (once again) Sorry it keeps breaking, it's a rather tricky bug and hard to watch out for when tweaking rendering of components. Thanks for reporting it though and please DO keep reporting it in case it breaks again :)

**Comment by ptsochantaris** [comment]
Hi @Karlotcha 

Just letting you know the new 1.3.6 update is up, including this fix, so you may want to update to that instead of the debug build provided for more stability and speed. Thanks again for reporting the problem, hope you don't see it regress again :)
