### ISSUE TITLE
Feature-Request: Group by Org

### ISSUE THREAD

**Issue by Luzifer** [ptsochantaris/trailer#214]
As a user currently watching 140 repositories in 8 organizations (one of them the company I'm working for) it would be great to have a feature to allow me to group the pull-requests / issues in Trailer. If that grouping would be collapsible it would help me focus on which scope currently is important and don't see my companies PR/issues while working on my spare time projects. Also I would not longer have to search for the issues of my spare time projects vanishing between hundreds of issues in my companies repos.

**Comment by ptsochantaris** [comment]
Hi @Luzifer!

There are two simultaneous and valid issues here. One is actually far easier and closer than you think, and one would be complicated. Let's have a quick look at each:

- The "easy one" - I.e. focusing on a specific subset of items for an org: I am currently working on adding specific filters to Trailer, that is, specifying "repo:XXX" on the filter line to filter specifically for a certain repo or "user:YYY" to filter specifically for a certain user (and you can combine). Adding "org:ZZZ" should be quite easy and probably something I ought to have added anyway. I could have a test build with that very soon if that's something that would make your life easier. It won't mute notifications for other things of course, but then if you wanted that much separation you'd probably want to import/export profiles from the "other" section anyway.

- The "complicated one" - i.e. Creating a hierarchical structure in the UI grouped by a property: It does sound like a good idea initially, but quickly descends to complexity and special cases. For instance, it's been requested before to have a "group by repo" option, this would be something similar (group by org) While this is theoretically possible, I've got a feeling it's both overkill and impractical, since if you're working with large lists of things you'd have to keep scrolling to the appropriate org/repo etc, whereas having typed org:XYZ in the filter bar, it stays there, and your menubar count also stays updated according to it. Also, how would you group stuff? Inside the Mine/Participated/All structure or above it (i.e. each org having Mine/Participated/All) - it quickly gets complicated when we have 2 layers of grouping.

So what do you think? Would the first case cover a lot of what you need, or am I missing your point? I already have a version with the filters ready (I was literally working on that today :)), so I'll quickly add the "org" parameter (that should have been there in the first place :)) and attach a version here for you to try out and see if it helps.

Let me know your thoughts!

**Comment by ptsochantaris** [comment]
So, this is the current test build: https://www.dropbox.com/s/g0rd6nhnawbh5l1/Trailer-avatar-test.zip?dl=0

It just occurred to me that you can actually just use the repo: filter to limit items for a specific organisation, just use repo:orgname/ (including the slash at the end to ensure it doesn't match a repo name) ought to do it.

Let me know your thoughts on this, if you think specific org: and repo: tags are a better idea instead, and how much this covers what you need in the first place, of course.

**Comment by Luzifer** [comment]
Works nice and fits my usecase (filtering for the current scope) 100%! :+1: 

Just one small thing maybe an own issue: If I type in the search field and want to move the cursor with arrow keys I'm not moving the cursor but switching between issues and PRs…

**Comment by ptsochantaris** [comment]
Nice, that's great to hear! Let me know if you spot any bugs with it.

Also, I'd like your opinion - Right now options aren't incremental, for instance, using two "label:" filters won't get items with either label. Eventually I hope to make it so, but how important do you feel this would be for you as a user right now?

Finally, you're definitely right about the left-right keyboard issue, but I'm not sure how to resolve it. There are these conflicting requirements:
- Left/right should always move between PRs and Issues, if both are visible
- Left/right should move the cursor inside the filter field when it is focused
- Filter field should always be focused/selected so the user can start typing after opening the menu

The only thing I can think of is yet another option in the "keyboard" tab to require "alt" left/right to switch between PRs and Issues (or not), leaving vanilla left/right available for the filter field. I'm not keen to keep adding options in prefs all the time, but these new filtering options upgrade the use of the filtering field quite a bit, so like you've discovered it's important for it to be easily editable with the keyboard. What do you think about that approach?

**Comment by Luzifer** [comment]
For me using two filters seems like optional but nice to have… Currently I'm in a region where I have between 70 and 100 PRs and ~150 issues at max… After filtering by `repo:` I have a good overview… Though it would be nice to say something like `repo:luzifer bug` to get all issues with `bug` in the title and in repos starting with `luzifer`…

The issue with switching between PR and Issues my opinion is you could make that <kbd>alt</kbd>+<kbd>←/→</kbd> and it would not loose its function but restore ability to move within the input field.

**Comment by ptsochantaris** [comment]
Thanks for your feedback! :+1:  Yes, I think let's go with the "alt" option on the navigation (making it default, but I want an option to disable it for people who don't much care for the filter field and want fast keyboard navigation)

You should already be able to do "repo:luzifer bug" now and get the results you want, let me know if this isn't working for you. The thing is that for now you just can't chain multiple label: statements. I may look into doing it anyway for this release though, as it bugs me :)

**Comment by Luzifer** [comment]
Yep, you're right: `rep:luzifer code` is working as expecting. :+1:

**Comment by ptsochantaris** [comment]
Ok, here's an update: https://www.dropbox.com/s/0d5oam5njdddkah/Trailer-filtering-2.zip?dl=0

- Keyboard switching between PRs/Issues should be now with Alt-Cmd-Left/Right (Alt by itself overrode the "skip word" behaviour in the OS X textfield which was very useful in this case, so I added Cmd as well)
- Editing inside the filter field should work as expected
- Multiple terms on filters (ORed), and multiple filters of the same type (ANDed) :) So it stops bugging me.

So now, for instance, "label:bug,critical" will provide any items that contains labels "bug" or "critical", while "label:bug label:critical" will provide items that have BOTH labels "bug" and "critical" only.

**Comment by ptsochantaris** [comment]
HI @Luzifer 

Just wanted to let you know that the 1.3.6 update is up and includes all the above updates, and some further tweaks and fixes (including a separate "title:" search prefix) so I would recommend you update to that.

I'm going to close this specific issue for now, but please feel free to open new issues with related stuff.

Finally, thanks for all your feedback and help with testing this feature, it's been much appreciated!

**Comment by Luzifer** [comment]
Thanks for your work and the fast implementation of this feature! :+1:
