### ISSUE TITLE
Suppress PR notifications for failing builds

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#221]
Would it be possible to add support for suppressing PRs that are failing GitHub hooks? Generally, this means the PR did not pass the CI build but there might be other checks (hooks) wired into GitHub (like Code Climate checks and maybe others).

By supporting this, one wouldn't have to see PR notifications or see PRs in the list that are failing.

It would be nice to have a preference option to enable/disable this (as I realize some might prefer to be notified of everything). If a preference is added, it should probably be disabled by default so others are not surprised.

Here is an example (screenshot) where I have some PRs (with sensitive information pixelated out):

![pull_request](https://cloud.githubusercontent.com/assets/50245/9612121/eddb063a-50a0-11e5-9901-850e883d32f4.png)

The last PR failed CI (actually, it's not a very good example but the result of this is that it didn't pass). I would like to have a preference option I could enable that would be something in the `Display` preferences (maybe) that is `Ignore/hide failing PRs` or something along that line. If enabled, then I wouldn't see the last PR (or be notified of it) in the screenshot above because `all` checks didn't pass. Only when the PR passes all checks should it appear on the list and a desktop notification be sent.

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann 

Thanks for the detailed description! This feature makes a lot of sense, especially in many teams where PRs will only get reviewed if the branch is green, this could help prfioritize things.

As for the option placement, I would most probably put this in the Labels & Statuses panel, together with all the other CI options (Otherwise, out of context, there would need to be an awkward "you can't turn this on unless you are showing CIs and Statuses" kind of message in the Display section)

Something to watch out for when this is added though: I have, on occasion, seen a red CI status on a PR that didn't actually show up at GitHub (or rather, the status was red, then it became green, but it's still listed in the statuses). I'm worried this may lead to "false hiding". This is most likely due to Trailer showing the wrong data for some reason, but if you're planning to use this feature intensively, then perhaps we'll solve it sooner rather than later, as my understanding of CI statuses at Github remains a little limited. If you can show me a false status display and explain why that red status shouldn't be there, I'm sure I'll be able to debug it. Just giving you the heads-up that this may need to happen at some point though (OTOH this could be entirely because of bad CI configuration in the places I've seen this)

If you're not scared of that possibility, I'll be more than happy to make this tweak on the upcoming release, it shouldn't be too hard to implement.

**Comment by bkuhlmann** [comment]
Yeah, an option within the Labels & Statuses section makes a lot more sense, thanks.

Yeah, I'm happy to help and provide as much feedback and diagnosis as you need. I think this would be a welcome feature to help filter out some of the noise that isn't actionable or doesn't need one's immediate attention for review.

I'm also OK with the false positives as I generally check the standard GitHub notifications, in addition to Trailer, as a backup in case I missed something (generally, it's for other projects in the company that I'm not a part of but might want to scan for interesting learnings).

**Comment by ptsochantaris** [comment]
Great, will let you know when an upcoming beta build includes this :+1:

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann - I've just released the v1.3.7 update and this didn't manage to get in with all the craziness my work schedule recently. This feature is at the front of the queue for the next update though, and I will give you a shout in this thread as soon as there is a testable build with this feature (shouldn't be too long :))

**Comment by bkuhlmann** [comment]
@ptsochantaris No worries, thanks for the update...downloading now. Yeah, I'm just happy you have time to keep working on this in general. :) Looking forward to the next testable build.

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann,

Here's a link to a build which contains this feature in case you feel like testing it, and sorry for the long turnaround time on this.

It should be quite stable, but implementing it meant cleaning up (and broadening) some notification-related logic, so if you get the chance to try this out, keep an eye out for notifications - if you're seeing too many, seeing notifications for things that shouldn't show up, etc. or have suggestions on it, let me know.

https://www.dropbox.com/s/777yhlnlco6qphi/Trailer-1.3.9-test-1.zip?dl=0

Hope this helps reduce noise on your Trailer!

**Comment by ptsochantaris** [comment]
And another build, with a fix for the update mechanism: https://www.dropbox.com/s/goqmpmtau4w8p2d/Trailer-1.3.9-test-2.zip?dl=0

**Comment by ptsochantaris** [comment]
There was a bad issue with updates failing under El Capitan, so I pushed this build to release - you can get the final build from here. Hopefully there won't be any regressions here, but please DO let me know if you spot anything and I'll keep an eye out to make a quick point update if there are: https://github.com/ptsochantaris/trailer/releases

**Comment by bkuhlmann** [comment]
Awesome, thanks! I'll need some time to respond back on this but will let you know once I've put this to use and have feedback.

**Comment by bkuhlmann** [comment]
Well, I didn't intend for such a long delay in my response to this but I've been using the new feature and it is working great. With the option checked, no failing PRs show up. Unchecked, and I see them again.

Thanks for getting this into the release. Very happy to have this!
