### ISSUE TITLE
Pocket (watchOS) rapidly consumes battery when added as a complication

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#224]
I'm afraid I don't have a lot of useful info regarding this issue but I can definitely say that adding Pocket as a complication will eventually consume the battery at a rapid rate. Generally, a normal day of usage only consumes 45% battery (roughly). With Pocket enabled as a complication, the battery can be completely drained by noon.

It doesn't matter if the complication is being actively used on the watch face or not, only that it is added as a complication. Also, the rapid drain on the battery doesn't happen immediately. It might take more than a day before the battery begins draining faster than normal.

Upon noticing the battery rapidly draining, removing the complication won't solve the issue. The watch should be rebooted at this point.

I am using the following versions:

- watchOS 2
- Pocket 1.3.8

**Comment by ptsochantaris** [comment]
Wow, thanks for calling this in!

To be honest I have not experienced this issue, and I use a Trailer complication. In theory, watchOS will actually "throttle" mis-behaving complications to make sure they don't use up battery due to bugs or bad design, so my initial (but possibly wrong) reaction is to wonder is this is watchOS being buggy. This is reinforced by the fact that you say this happens even if you remove the complication, and more importantly the scale of drain that you describe is enormous - so it's not something I would have missed on my Watch, for instance.  I assume by the percentages you refer to the battery drain you're describing is on the Watch battery, right?

Still, there is code in the complication which I am not too happy with, especially how refreshes are handled, and this mainly boils down to the fact that watchOS application contexts (i.e. the data that is asynchronously "posted" by the parent iOS app which is then displayed by the glance and/or complications) seems to work strangely for complications, including how quickly data first shows up in complications when first added, etc. This was compounded by the relatively poor debugging support for complications in Xcode currently.

Sorry is this is a slightly vague answer, but my experience with watchOS 2 on the dev side of things has left me cautious about trying to "fix" bugs, in far more cases than I'd like it turns out watchOS is to blame for weird or undocumented behaviour which then gets corrected in the next release at which time the workaround ends up *creating* bugs, etc :)

That said, I'm going to be keeping a close eye on this, and will try removing/adding complications and see if this makes a difference over the next few days.

Just so I can try mirroring your setup, which face/complication type are you using?

Also, I wonder if this may be related and something I may need to throttle on the watch side, what's the *background* refresh minimum rate you have for Trailer on your iOS device?

**Comment by bkuhlmann** [comment]
Yeah, I've been hearing grumblings about watchOS debugging support so that is interesting to know -- that watchOS might be the issue too.

Some more details for you:

- When describing the battery drain, yep, it's the watch battery. I don't recall seeing a significant drain on my phone. Maybe it showed signs too but I'd have to try it again and watch (bad pun) that too. With the watch, however, you could look at the battery complication and see a percentage drop every couple of minutes.
- I'm using the Modular watchOS complication. With this complication, I generally have Pocket in one of the smaller complication windows (not the large one in the middle with the verbose text).
- I'm using the minimum auto-refresh settings, my phone configuration is:
    - Foreground refresh interval: 60 seconds
    - Background refresh interval (minimum): 10 minutes
    - Watchlist & team list refresh interval: 2 hours
    - Re-query statuses: Every refresh
    - Re-query labels: Every refresh

So, um, yeah, perhaps a bit aggressive. :) I don't have a lot of high traffic projects is one reason why they are this way.

**Comment by ptsochantaris** [comment]
Thanks for updating me and the extra info! I'll try mirroring your setup and see if there is any chance in my Watch battery usage :+1:

The settings you have don't strike me as aggressive to be honest - even if we'd assume that the new Watch-related code in Trailer isn't very good, they should certainly not result in the huge battery drain you are experiencing (mine are about the same)

Will be keeping an eye on this - definitely keeping it in mind when revisiting the complications code in the near future.

**Comment by bkuhlmann** [comment]
ok, sounds good, thanks! If find anything else, I'll post here as well.

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann,

watchOS 2.0.1 is out, and seems to include a lot of fixes to battery life issues, according to the release notes. If you get a chance to try out the complications again (with your charger handy, perhaps :)) let me know in case the situation improves with this version.

**Comment by bkuhlmann** [comment]
Will do. I'll need a couple of days before I can respond back.

BTW, I don't think this has anything to do with Trailer as I've experienced this with other complications as well but haven't been able to pinpoint what the root cause is. Will test the new update and respond back shortly.

**Comment by ptsochantaris** [comment]
No problem, take your time and let me know!

(In general, I am seeing improved performance of many things in watchOS 2.0.1, so it's encouraging)

**Comment by bkuhlmann** [comment]
Closing this issue. The watchOS 2.0.1 has been a big help to abating these issues. I've used several complications/watch face combinations without issue. It seems the root issue was really with watchOS and not Pocket.

**Comment by ptsochantaris** [comment]
That's good to know, and useful info in case anyone else encounters this issue on watchOS 2.0.0. Thanks for reporting and following up on this :+1:
