### ISSUE TITLE
Suggestion: Exclude results from search

### ISSUE THREAD

**Issue by Davidslv** [ptsochantaris/trailer#238]
Hi @ptsochantaris,

I was thinking if is possible to add a feature to the search where we can see all pull requests except the ones that have for example a title with `[WIP]`

I was thinking something like typing:

`! WIP`

And would show all the pull requests without `WIP`.

Hope it makes sense.
Thank you,
David

**Comment by ptsochantaris** [comment]
Hi @Davidslv, yeah, it definitely makes sense.

I like the `!` prefix, although we probably don't want a space between it and the term, since a space in the search field separates ANDed terms right now (i.e. `title:UI title:tests` will list items that contains both "UI" and "tests", so `!WIP !IGNORE` will end up only ignoring results that contain *both* WIP and INGORE).

However, like with other search terms, we can also use the OR syntax, like `!WIP,IGNORE` which will mean ignore any result with either WIP *or* IGNORE (or both).

Ofcourse now I'm tempted to generically introduce this to the other other prefix terms as well, like `!user:ptsochantaris` (i.e. hide ptsochantaris from the list) or `!title:UI` for instance :)

Reserving the right to tweak the above, but, yeah, in general the "!" operator sounds like a good idea and a straightforward addition :+1: Stay tuned!

**Comment by ptsochantaris** [comment]
Hi David!

A new update is up which should include this feature now. Give it a go and let me know if it's what you had in mind. You can do things like "!WIP" that you mentioned, and you can also combine stuff, like "label:feature,!WIP" for instance.

Hope this makes you life easier! Be sure to let me know if you spot any crashing or logic issues with it.

**Comment by Davidslv** [comment]
Hi @ptsochantaris, it works great for me, thank you so much for this :+1: :tada:

**Comment by ptsochantaris** [comment]
Great stuff!

Thank you for suggesting this feature, it's very straightforward, makes a ton of sense, and was implemented quite painlessly :) Keep 'em coming!

Note on search: Always keep in mind you can search for PRs and Issues as well on the go from the iOS home screen (if you use Pocket Trailer), as the more recent versions have Spotlight integration, although you can't use the more advanced search terms like above. Still useful for quick lookups though, just pull down on the home screen and type a PR or issue number, or some keyword, or PR author username, etc).

If you have more suggestions on the search stuff (or anything else) please *do* open new issues, I have the feeling that it can become far more powerful with simple-and-direct changes like this one :+1:

**Comment by moertel** [comment]
Thanks for this, @ptsochantaris. I just want to point out that I found this solution a bit unintuitive. I expected `-label:foo` (like in the Github search) to work but tried `!label:foo` as well, to no avail. So, glad I found this issue and a solution to blacklist filtering. Maybe think about adding a small documentation section to the README.
