### ISSUE TITLE
Keyboard method to Filter dropdown

### ISSUE THREAD

**Issue by thomaswrenn** [ptsochantaris/trailer#239]
When opening the Pull Request dropdown with the keyboard shortcut there should be some way to focus the filter field (or it should be the default and accessible via Command-F and/or using the up arrow with the top Pull Request selected) so you can quickly filter and find a Pull Request, select it and open it all without the mouse.

Right now the filter field does weird constraint solving animations when the Pull Request dropdown opens so maybe it's a bug that you can't do this suggested behavior.

**Comment by ptsochantaris** [comment]
Hi @thomaswrenn - More than happy to look into the issue, but there might be something else going on, since the filter field ought to be already focused by default when you open the dropdown via the keyboard shortcut. So you can type, navigate using the arrow keys, and press enter to open PRs (or Cmd-C to copy the URLs, for instance) as well as ESC to close the window.

Are you not getting that? If so, what OSX version are you running? Another thought: Is perhaps the keyboard combination you are using to open the dropdown somehow shifting the focus?

Or have I just misunderstood your meaning? :) If so I apologise. Let me know on the above and let's see if we can fix it!

**Comment by thomaswrenn** [comment]
Yep, I think you were right that I must’ve had some other app doing
something on the same keyboard command cause it’s working as expected now.
Sorry about that.

**Comment by ptsochantaris** [comment]
No problem, I'm glad that's all it was.

If you *do* notice something weird with keyboard focus in the future, or any clash between Trailer and some specific app, please do open a new issue and let me know!
