### ISSUE TITLE
Trailer OSX notifications do not clear

### ISSUE THREAD

**Issue by pk-nb** [ptsochantaris/trailer#244]
Hi there! Thanks for such a great tool. I'm having an issue where notifications from trailer are not clearing through the "X" button.

<img width="319" alt="screen shot 2016-03-22 at 11 14 10 am" src="https://cloud.githubusercontent.com/assets/1911028/13960799/6a855438-f01f-11e5-8c9c-4610faf4cde6.png">

All other notifications are clearing out—but trailer's persist (even after a NotificationsCenter process force kill). Is trailer is failing to respond to notification clear events?

**Comment by tooluser** [comment]
I've seen the same thing!

**Comment by ptsochantaris** [comment]
Getting the same thing here - I thought it was my OS X installation that had gone weird. Thanks for reporting this, I'll look into it ASAP. It may have something to do with the new added custom actions, they may be causing a bug in OS X.

Stay tuned, will have more info on this soon.

**Comment by tooluser** [comment]
Thanks!

**Comment by ptsochantaris** [comment]
Ok, have figured this out - it has to do with a peculiarity of user notifications in OS X. It seems that if they have custom actions (see "mute" or "mark as read"), then they MUST also have a custom identifier field set, otherwise Notification Centre (or even the app itself) can't dismiss them! This is a sort-of bug in OS X I guess, and I will file a radar later on, but for now I'm going to send up an update that:

a) Will clear up your notification centre from the Trailer spam (unfortunately this will remove all notifications the first time, as the app can't selectively remove notifications due to the aforementioned bug) but most importantly:
b) All new notifications will be demisable from the notification centre.

Sorry for this hiccup guys, I'll ping you as soon as the new version is up.

**Comment by ptsochantaris** [comment]
Ok, new version is now up, go ahead and update and the issue should be corrected. As a small bonus, using identifiers means that you won't ever get any duplicated notifications in case Trailer is restarted sometimes, which could occur.

Let me know if it corrects the issue for you!

**Comment by pk-nb** [comment]
@ptsochantaris Updated and it's fixed! Thanks you very much for the quick response!

**Comment by ptsochantaris** [comment]
Great to know! I'm glad it's fixed.

I filed a radar with Apple about the issue, hopefully they'll either update the docs or fix the behaviour so other devs don't run into this in the future.

I'm going to leave this ticket open for a little bit if that's ok, so any user who is experiencing this can find out that there is this update out and quickly upgrade.

Once again, thanks for reporting the issue! Keep opening issues if you spot anything else.
