### ISSUE TITLE
As a developer, I would like Trailer to display new PR's where I am mentioned

### ISSUE THREAD

**Issue by onowak-censio** [ptsochantaris/trailer#249]
When a colleague creates a PR for a repo I am watching, they will generally @me to notify me to review. I would like Trailer to show me those PR's in a "mentioned" section where I am not already participating.

By the way -- great app. Very useful.

**Comment by ptsochantaris** [comment]
Hi @onowak-censio, I'm glad you're finding Trailer useful!

If I understand your requirement correctly, you know about the "move items mentioning me / my teams" options already, but they're not quite what you need - what you're proposing is a new "mentioned" section, where items you are not participating in (i.e. haven't posted comments) but have been mentioned in, will be moved to. Is that right?

That does make sense, but now for the big question :) Does this section come before or after the "Participated" section? I would suggest it comes after, since it represents a step down in terms of involvement with an item, but would like to hear your thoughts too.

**Comment by onowak-censio** [comment]
@ptsochantaris yes. your understanding is correct. 

i agree having the "Mentioned" section coming after "Participated" makes sense. :)

**Comment by ptsochantaris** [comment]
Hi, here's a build with a version of this feature ready for trying out. The more I think of your suggestion, the more I think it's really useful to have a distinct "mentioned" section separate from participated, so I've reused the "move items to participated on comment/mention" options to now target this section. This means that these options will now send items to the "mentioned" section rather than the participated section, and this makes both sections' purposes much clearer. Note that you *will* need to enable those options for items to move to the "mentioned" section, but I assume you're already using their previous versions already, so they'll already be on for you.

https://www.dropbox.com/s/x0xq26oodiammkl/Trailer-mentions-test.zip?dl=0

One point of contention for me is if it's a good idea to receive comment notifications from the mentioned section or not. Since this section is essentially just a sibling of the participated section, I have kept notifications & badges enabled to be consistent, and I feel it's the overall best approach, but would definitely welcome your thoughts on this: Should the mentioned section be special in that it *doesn't* badge/notify items, in the same way the "all" section doesn't by default? Or to be more precise: is it worth having an *option* to stop the mentioned section badging/notifying of new comments etc?

**Comment by onowak-censio** [comment]
@ptsochantaris thanks for the build! me and a colleague will test this out and get back to you with feedback. we open PR's for each other daily, so we will have ample opportunity to test this feature out in the next couple days.

again - thanks so much! :D

oli (and scott)

**Comment by ptsochantaris** [comment]
That's great, looking forward to your feedback! Just to keep your build up to date, here is the latest (RC1) of the upcoming release, hopefully it sorts out any issues which you may see in the above build: https://www.dropbox.com/s/zii3qtj2wzwznw8/Trailer-1318-rc1.zip?dl=0

**Comment by ptsochantaris** [comment]
Just a quick note: If you are running any OS X before El Capitan, this development build will not migrate properly to the final version. Please be sure to export your settings before upgrading (or just do an export now and have it handy :)) so you can re-import them after the upgrade, or you will lose all your configured repos.

**Comment by onowak-censio** [comment]
@ptsochantaris thanks, paul. this RC is good to go. love the "Mentions" section. it makes things so much easier. very cool.

**Comment by ptsochantaris** [comment]
Fantastic, I'm glad it's what you expected and you're finding it useful 👍

Please take heed of my warning above about updating to the final version when it's up (should be in the next few days)

**Comment by ptsochantaris** [comment]
Ok, 1.3.18 is now up. Thanks again for your suggestion, and feel free to open more issues with suggestions or ideas you may have in the future.

Also: remember the warning above, make sure you export your settings before upgrading from the intermediate development build or you will lose them!
