### ISSUE TITLE
high amount of CPU usage on latest version

### ISSUE THREAD

**Issue by cmluciano** [ptsochantaris/trailer#259]
Since upgrading to the latest version I am seeing a huge spike in CPU usage from Trailer (sometimes up to 200% +). Is this expected with some new threading? This causes my fans to go haywire and limits my battery.

**Comment by ptsochantaris** [comment]
No, there should be no CPU usage at all, except when Trailer refreshes data from the server. Even when it syncs data, though, any spikes should be very short, unless you've just added a lot of new repos or something like that (which I'm assuming you haven't)

Based on the previous issue you were having with crashes, I'm wondering if your database isn't perhaps corrupted, or there is a zombie instance of Trailer perhaps running in the background? Suggestions:

a) Try rebooting to make sure there is only one Trailer process running on your desktop.
b) Activate logging to see if there are any operations that may be stuck in some sort of loop because of a bug.
c) Reset Trailer: Export your settings, quit, backup and then remove the directory at ~/Library/Application Support/com.housetrip.trailer, and set up Trailer again. Ignore the quick-start and re-import your settings. After a sync, things should be reset back to where they were.

(BTW in case you had logging on from the previous issue and haven't turned it off, you should, because logging is very CPU intensive and will slow things down a lot)

Let me know how it goes!

**Comment by cmluciano** [comment]
I hard-recycled my config and this seems to be fixed now
