### ISSUE TITLE
Consistent crash while refreshing comments

### ISSUE THREAD

**Issue by RobinDaugherty** [ptsochantaris/trailer#263]
Here's the crash: https://gist.github.com/RobinDaugherty/220ce4202a30a102caef932538ceb198

This started with 1.3.17 and is still happening with 1.3.21. I will try this in Xcode and see if I can get more details about the request that is being parsed.

**Comment by RobinDaugherty** [comment]
I was able to work around the crash by disabling comment notifications.

**Comment by ptsochantaris** [comment]
Hi @RobinDaugherty and thanks for calling this in and posting the crash report.

Sorry to hear you're getting this, let's get it fixed.

There seems to be something going on with a string handling corner-case. Just in case, could you try the latest RC as I've been doing a lot of cleanup on string handling? https://www.dropbox.com/s/6vo013rt86h3imt/trailer-140-rc8.zip?dl=0

If you *do* have the ability to run the latest master branch on Xcode, that would certainly help locate the crash, otherwise I can create a debug-mode build whose crash log could be more helpful in diagnosing this crash.

Let me know how the RC goes first and I'll get right onto that debug build otherwise.

**Comment by ptsochantaris** [comment]
Version 1.4.0 is up now, so if the RC is working well for you then you probably want to upgrade to the final. If you are still having this issue, let me know and I can set up that debug build for you and we can track the issue down.

**Comment by ptsochantaris** [comment]
Hi, just wondering if you had any luck with the new update or any further feedback?

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this issue for now. Feel free to reopen if you are still having issues.

**Comment by RobinDaugherty** [comment]
Sorry I couldn't help before @ptsochantaris it looks like you've fixed the problem in the latest release. Thank you!
