### ISSUE TITLE
Other API support

### ISSUE THREAD

**Issue by zkendall** [ptsochantaris/trailer#264]
I've been using Trailer for months now and love it. Perfect balance of functionality, minimalism, and customizability.

However, now I'm on a project using Stash/Bitbucket Server; any plans to support other APIs other than GitHub?

**Comment by ptsochantaris** [comment]
Hi @zkendall and first off, thank you so much for your comments on Trailer. I'm really glad you're finding it useful.

Since I too worked on a project on Bitbucket, I thought about supporting the API for it in the past. The problem is that Trailer is a very GitHub-oriented tool, because it grew organically around the specific GitHub API and that internal data model (and features). Supporting Bitbucket and other APIs would involve either:
- A major rewrite to create an API-independent internal "Trailer" info store + logic which would be a superset of multiple APIs and which knows the source of each data item in order to accommodate the behaviour and intricacies of each "source" or
- Shoehorning the Bitbucket API (and others) into what's possible with the GitHub API (i.e. creating an "adapter" that "fits" BB data into the existing GH-oriented data store and logic.) That would mean that in some places we'd need to have defaults for things that are in the GH API and not BB API, and in others chose to "amputate" features and/or info that is in the BB API and not GH API. Adding to this, would be the issue of signalling the boundaries of certain interactions to the user, i.e. ensuring that "sorry, this option won't work on a PR from BB" is either handled internally when offering options, or just pestering the user with unexpected "sorry, not on this service" messages, making a bad experience.

Either of the above would be compounded by my relative lack of experience using BB compared to GH, meaning that I wouldn't know what kind of "weights" to attach to features or abstractions when deciding on features (last time I used BB it was mostly just like GH, but I have a feeling I was just using the lowest-common denominator set of features)

And finally, another issue would be building separate server authentication and configuration for BB, an additional time cost as well.

Due to sheer numbers of GH vs BB users (plus the fact that I work on this for free) the first scenario would be impractical, while the second scenario would probably be more of a stopgap - i.e. just paying lip-service to BB instead of letting Trailer be a genuinely useful native tool for BB.

Now, of course, this is pretty much what I'm thinking right now, and as with everything it can definitely change :)

If you think either of the two cases above are based on misconceptions about how distant the BB functionality is from GH, or if I'm perhaps overestimating the effort involved (for all I know those two could just be clones, i.e. making the 2nd scenario a far less tricky proposition) then I'm more than happy to learn more. Let me know your thoughts on this, more than happy to keep discussing it, since you're definitely right, overall it would definitely be a nice to support BB if possible.
