### ISSUE TITLE
PRs that are assigned to you are not recognized as being mentions

### ISSUE THREAD

**Issue by WilsonChiang** [ptsochantaris/trailer#269]
It seems like when a PR is assigned to you but you are not mentioned it does not properly show up under the mentioned column.

My settings are setup so that I only see PRs I participated in.

**Comment by ptsochantaris** [comment]
Hi @WilsonChiang - An assigned PR won't move to the Mentioned section on the virtue of being assigned. You can control where it ends up from the setting in "Display" on the upper-right: 

<img width="350" alt="screen shot 2016-06-14 at 17 37 58" src="https://cloud.githubusercontent.com/assets/521581/16051315/2c56ee7c-3257-11e6-829f-f56840ac1699.png">

Or have I misunderstood your question?

**Comment by WilsonChiang** [comment]
Hi @ptsochantaris. This is an issue with the PR not showing up at all. I'll try to reproduce but I think it may be an issue with GH allowing multiple assignees from last week. Could it be an issue of checking for only the first user under the assumption that a PR can only have one assignee?

**Comment by ptsochantaris** [comment]
Oh, I see. That is entirely possible, yes. Trailer will only use the "assignee" field from the PR or issue to check if an issue is assigned.

Since it seems items can now have multiple assignments, I see a new assignees_url field exists, which Trailer can query and check for assignment across many users.

Will add this to the sync logic, stay tuned 👍

**Comment by ptsochantaris** [comment]
Hi.

Unfortunately, investigating this a bit further, I hit a snag, since it seems as if the API to check for multiple assignees is in development and not yet available. I'm going to leave this issue open, and as soon as the APIs for supporting this are available will definitely resume adding it, as I agree it's definitely an important feature to support.

**Comment by WilsonChiang** [comment]
https://developer.github.com/v3/issues/assignees/

Looks like its supported now @ptsochantaris

**Comment by ptsochantaris** [comment]
Hi @WilsonChiang, unfortunately it's still not there, as these calls are repo-wide, and just list users.

From what I understand, the API is currently being expanded to include an "assignees" hash in issues/prs in addition to the "assignee" (singular) field, but that is only available if you provide a specific testing header (its pretty much the same thing when it comes to supporting reactions as well)

(Note: for some reason now I can't find even that in the API documentation, although I may not have looked hard enough)

Note: If you feel I may have missed something or think there is a call to get a list of (multiple) assignees for an issue/pr, please DO set me straight, I'd love to implement this sooner rather than later!

**Comment by ptsochantaris** [comment]
Hi @WilsonChiang - It turns out you were right after all, I was just looking around to see if this feature was going to be added, and it turns out it _was_ added on the 12th, but only announced in the API blog (I can see the "assignees" hash in the API return data now). I was confused because the documentation still has the "needs the experimental headers" tags :-/  I thought I'd let you know :) Will add this to the 1.5 beta ASAP.

**Comment by ptsochantaris** [comment]
BTW just a small note, to test this I'm going to add you as a co-assignee for this issue, so I can see how the API reports this. Please just ignore any notices that come from this :)

**Comment by ptsochantaris** [comment]
Ok, turns out I can't do that, never mind :) I'll find another way around this.

**Comment by ptsochantaris** [comment]
Ok, beta build updated. If you're feeling moderately adventurous, give it a go on #289 and let me know if it helps!

**Comment by WilsonChiang** [comment]
Awesome, thanks! I'll give it a shot.

**Comment by ptsochantaris** [comment]
Hi, I just remembered I haven't closed this issue yet, as it ought to be resolved for a while now :) As always, feel free to open new issues in case you spot any problem or have any suggestions.
