### ISSUE TITLE
The "Refreshing ..." message is barely visible

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#276]
When when 1st refresh and you have no issues/pull requests fetched from GitHub the `Refreshing ...` text is displayed like this:

![2016-06-17_1341](https://cloud.githubusercontent.com/assets/1277526/16155135/ad299516-34b6-11e6-85e9-8c933a9602a3.png)

Not sure where the issue is, but it's barely visible (the `r` and `i` letters specifically). I think this happens when I combine default font used in Yosemite and translucency feature.

**Comment by ptsochantaris** [comment]
Are you using a non-retina display perhaps? If so, font rendering over the translucent container ends up looking a bit bad when the text colour is light gray like that - something to do with alpha channels used as part of anti-aliasing by OS X. I think this issue is less prominent on El Capitan TBH.

I may look into making this message a bit larger or darker in the next release, but TBH I'm not sure there's too much that can be done here, especially since it's a temporary message.

**Comment by aik099** [comment]
Yes, I'm using external 21.5'' display connected to MacBook Pro via DVI-Thunderbold adapter.

Making text blank would probably solve the problem completely.

**Comment by ptsochantaris** [comment]
Hi, going to close this issue for now but will keep colouring/font size for non-retina in mind during the next UI refresh 👍
