### ISSUE TITLE
All items lost snoozing status after upgrade to 1.4.3

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#282]
I've manually snoozed lots of items. After upgrade from 1.4.2 to 1.4.3 all items (issues, PRs) suddenly lost their snoozing status without anybody actually adding comment to them on GitHub.

This might be related to new setting, that will autosnooze issues after X days.

**Comment by ptsochantaris** [comment]
Yes, this is something that will happen when you're adjusting the auto-snoozing setting as it has to un-snooze everything and re-snooze them according to the new ruleset - but only for items that are snoozed "forever" (which is what auto-snooze sets and handles). This has to happen or tweaking the auto-snooze setting will end up with everything getting snoozed.

However, I'm now thinking about perhaps setting a slightly different snoozing duration for auto-snoozed items, so changing the setting won't affect manually snoozed items, this may be a better way to go. Stay tuned.

**Comment by aik099** [comment]
I thought, that items snoozed manually using `Forever` snoozing preset won't ever unsnooze until they're actually awaken by GitHub event (e.g. new comment added).

I haven't changed any snoozing presets either. What I did is changed `auto snooze after X days` from `never` to `1` and then back to `never`. I guess that lead Trailer to think, that I want to unsnooze all items that are older than 1 day.

**Comment by aik099** [comment]
> However, I'm now thinking about perhaps setting a slightly different snoozing duration for auto-snoozed items, so changing the setting won't affect manually snoozed items, this may be a better way to go. Stay tuned.

Agreed. Manually snoozed items can be unsnoozed only manually or via GitHub event.

**Comment by ptsochantaris** [comment]
Yeah, the change in settings had to wake up all the Forever items to apply the new rules to them - which is retrospect is a bit unintuitive. I'm tweaking the auto-snoozing to use a "special" date (Forever - 1 second) for snoozing, so that then it only wakes up items with that special date, and not items which you manually snoozed Forever. Update will be up in a few minutes, will give you a shout :)

**Comment by aik099** [comment]
So if I've snoozed item manually using `1 month` preset and set to auto-snooze after `1 day`, then item shouldn't wake up earlier than `1 month` (or github event) regardless of what changes I made in Snoozing tab in settings. It's not that only `Forever` preset is special.

**Comment by ptsochantaris** [comment]
Exactly. But in the previous build both manual and auto-snoozing used the Forever date, so changing the auto-snoozing setting would wake up items that were manually snoozed with Forever. This is what caused your issue. Non-forever Snoozed items would be unaffected anyway. The fix changes the date used to auto-snoozed items, so the app will only wake up those when the setting is changed. All others should remain untouched.

Ok, hotfix should now be up. Go ahead and install. Tweaking the setting now should no longer affect your manually snoozed items (Forever, or otherwise). Caveat: This bug means that items that were now already snoozed by auto-snooze will stay snoozed (as if you had manually snoozed them). But I don't think that would be a big issue for you. To avoid this, set the auto setting to 0 before installing this new build.

(Another caveat: If you manually wake up an item, it no longer becomes auto-snoozable, for obvious reasons, no matter what you set the auto setting to.)

**Comment by aik099** [comment]
I've updated, but I guess I'll see no visible changes.

Is there any faster way to snooze item via snoozing present, then:

1. right click on item
2. use mouse to move to `Snooze...` menu
3. use mouse to select `Forever` (preset name)

?

Considering that all my forever snoozed items are now visible again I have to snooze them again (I have ~150 issues to snooze and ~40 PRs to snooze) spending lot of time on these actions can be avoided considering that for each item I already know (from last time) if I want to snooze it or not.

**Comment by aik099** [comment]
Maybe the menu can be reworked to:

1. have separate group (after new separator), where all snoozing presets are placed
2. all menu items in that group would start with `Snooze: ` prefix
3. all menu items in that group would have some auto-generated shortcut, like `Command+0`, `Command+1` and so on so there never will be a conflict when new presets are added
4. for 10+ snoozing preset there won't be any shortcut

Since user can reorder snoozing preset by popularity then ones, that are often used will get their shortcut.

**Comment by ptsochantaris** [comment]
True, you shouldn't see much difference, except that playing around with the new setting should no longer wake up previously "forever" snoozed items.

I totally agree, some sort of faster snoozing makes a lot of sense. I was thinking of the hotkey approach rather than making the main context menu very long, something more in line with what you describe (i.e. Cmd-S-[Number]). This has already been mentioned here: https://github.com/ptsochantaris/trailer/issues/280 so let's pick it up over there.

Have a play with the new option to see if the issue of auto-wakeups you mentioned have gone away, and we can proceed to close this issue if all is good.

**Comment by aik099** [comment]
> Have a play with the new option to see if the issue of auto-wakeups you mentioned have gone away, and we can proceed to close this issue if all is good.

Fix confirmed. The forever snoozed item haven't auto-wake up when I've changed auto-snoozing setting back and forth.

Thank you.
