### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by jagreenwood** [ptsochantaris/trailer#286]
I'm seeing a crash on launch during the syncing operation.

It seems the problem is with the forced downcast in
```
func actualHeaders() -> [NSObject : AnyObject] {    
    return NSKeyedUnarchiver.unarchiveObjectWithData(headers) as! [NSObject : AnyObject]
}
```

Making this function return an optional resolves the crash but seems to cause problems elsewhere, such as consistent failed fetch state and crashes when fetching from the moc. 

It should be noted that several of my colleagues are _not_ seeing this crash; I'm not sure what it special about my account / repos / install.

**Comment by ptsochantaris** [comment]
Hi @jagreenwood and thanks for calling this in and for your investigation.

Very strange that this should fail, it looks as if something not quite right "wedged" itself in Trailer's cache and is now exploding when Trailer is trying to pull it out.

This code basically takes the previously marshalled headers from an older call and "expands" them back to their original datatype (i.e. pretending to have just freshly come down from the server). What's happening is that the un-marshalling is failing for some reason. In theory, this should never happen, but it seems you have run into a corner-case!

The easiest way to fix this would be to (a) export your settings and (b) nuke the database directory at ~/Library/Application Support/com.housetrip.Trailer then restart and re-import your settings.

Hopefully this should fix your crash and you should be able to continue using Trailer without issue, but if it's repeatable let me know and I'll look into perhaps expediting the fix for this bit of code (it basically needs to fail gracefully, so that if the headers are invalid for whatever reason, the cache entry simply should not be used)

Let me know how it goes!

**Comment by jagreenwood** [comment]
@ptsochantaris nuking the cache cleared it up. I'll let you know if I'm able to reproduce it at any point. Thanks!
