### ISSUE TITLE
Corrupted database; any hope of recovery?

### ISSUE THREAD

**Issue by CraigCottingham** [ptsochantaris/trailer#287]
Trailer has started crashing on me:

```
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=259 "The file couldn’t be opened because it isn’t in the correct format." UserInfo={NSSQLiteErrorDomain=11, NSUnderlyingException=Fatal error.  The database at /Users/craigc/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
```

Is there anything I can do short of deleting my SQLite database and restoring from a backup?

**Comment by CraigCottingham** [comment]
Also, it's not high priority, but some kind of alert from Trailer itself would be useful here. I had to go looking in Console.app to figure out why Trailer wasn't launching.

**Comment by ptsochantaris** [comment]
Hi @CraigCottingham and thanks for reporting the error.

Unfortunately there's not much that can be done if the file is corrupted. Core Data usually operates SQLite with very strict safety parameters by default, but because Trailer doesn't hold mission critical data (or any data that is not re-creatable for that matter) it operates the store with fewer safety features on to gain performance, and in very rare cases of power failure or a system crash it can lead to a corrupted store.

I would definitely recommend just restoring the com.housetrip.Trailer directory in Application Support from a backup.

However, you're absolutely right, Trailer ought to have given you a UI warning about this and not just crashed. I'm making a note to add a warning if this occurs, and possibly include an option to reset the DB on that dialog.

**Comment by ptsochantaris** [comment]
Just wanted to update you and let you know that this should improve on later versions, I have added a warning dialog to the latest beta: https://github.com/ptsochantaris/trailer/issues/289

It looks like this:
<img width="532" alt="error" src="https://cloud.githubusercontent.com/assets/521581/17477587/0458357a-5d5e-11e6-8805-df6b382c3b37.png">
Let me know if you have any thoughts and suggestions on this.

**Comment by CraigCottingham** [comment]
👍

**Comment by ptsochantaris** [comment]
Closing this issue for now. Version 1.5.0, which is now up, includes the above view as well as the changes to make the DB storage more resilient. Please feel free to open further issues if you encounter problems.
