### ISSUE TITLE
Hide number of PRs in menu bar

### ISSUE THREAD

**Issue by rossgardt** [ptsochantaris/trailer#293]
Is there a setting that hides the PR count? I could not find anything.

![screen shot 2016-09-08 at 10 59 54 am](https://cloud.githubusercontent.com/assets/234840/18343519/fe760830-75b3-11e6-8eef-2a76d0443bb2.png)

Best,
Benedikt

**Comment by ptsochantaris** [comment]
Hi @rossgardt 

There isn't one, yet :) Something I wanted to add for a while and it's on the TODO list.

My biggest "block" was debating how to display the "X" state if network or sync is down for whatever reason. I was thinking of making the icons red in this case, what do you think?

**Comment by rossgardt** [comment]
Nice to hear. I like the minimalism on Mac OS, so this feature would fit really nicely.

Regarding the visualization of the "no connection" state, I assume that it is repetitively retrying to connect to the server. For me, this still is the process of "refreshing", so I would just gray out the whole icon - again, to keep it as simple as possible. (Unfortunately, the [UX guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW12) on the Menu Bar icons are very thin  😕)

Nonetheless, I  think there should be a hint after X tries that there is a problem. My assumption is that a developer who is actively working with Github/Trail would realize that early enough. I mean you could add a hint in the popup panel:
![screen shot 2016-09-08 at 2 29 17 pm](https://cloud.githubusercontent.com/assets/234840/18349286/e958e7a2-75d0-11e6-8435-9a01a5899c1b.png)

Another situation of "sync is down" would be if the token is invalid. But this should trigger a dialogue and should not be indicated in the menu bar.

Hope this helps.

Best,
Benedikt

**Comment by ptsochantaris** [comment]
Hi @rossgardt 

Thank you for the input. I totally agree with the minimalist viewpoint, since in general I'm less interested in now many PRs or Issues exist, only that I can access them :) However this is not always the case, as some organisations (for instance, HouseTrip where this project was born) use the number as an org-wide code review "pressure" indicator (the original purpose of Trailer was to try and reduce the PR backlog :)) I too sometimes glance at the number to quickly check if, for instance, there have been new Trailer issues recently.

However, the above is not an argument against having the option to hide the numbers, this is more of an argument for highlighting new items that have just been added to a section (and the menu indicator as a consequence) - a feature that would probably sit well as a sibling addition to the feature we're discussing right now. Will think about this some more... :)

Thinking a little more about this feature specifically I realised that a red icon would actually translate as *unread comments* in a menu, so my initial suggestion probably doesn't make all that much sense. It probably makes more sense to change the icon into the red X in case of failure (and there is always the option to avoid reporting errors in the API server options for ultra-minimalists :))

I totally agree with you about reties and not failing immediately. Fortunately Trailer does this already when syncing, i.e. out of, for example, 200 calls, if one or more fail with a timeout or connection error, they are immediately put on a queue and re-tried after a short delay a few times.

So when you see a sync succeed (or not) at the end, it may or may not have included some endpoints being retried. This was added relatively recently because syncs would fail if some endpoint at GitHub was being deployed or a load balancer was leading to a 502/503 HTTP error, and this would cause the entire sync to fail.

I'd be more hesitant to add a warning inside the menu window, as that would only be revealed to the user after the opened it, and they may not have cause to open it unless they see unread comments, if you get my meaning.

Hope this makes some sense. Let me know if you have thoughts or comments on any of this. Currently I'm polishing off 1.5 for release, but I'm hoping to put this feature on queue for 1.5.1.

**Comment by rossgardt** [comment]
I think this all sounds reasonable :-) I am looking forward to the new features in the 1.5 release!

Best,
Benedikt

**Comment by ptsochantaris** [comment]
Hope to "ship" it soon! As always feel free to create issues about errors or features you may like.

If it's ok with you I'd like to keep this issue open until this feature is added - helps maintain a useful TODO list in my Trailer :)

**Comment by rossgardt** [comment]
Of course :-) Thank you!

**Comment by ptsochantaris** [comment]
Just a quick note to let you know I'm not ignoring this feature, I just haven't been able to do much Trailer work for a while. It's still in the TODO list.

**Comment by ptsochantaris** [comment]
Hi, so, here's a build of 1.5.2 that should do what you need :) I'll be testing it a bit and if it's good I'll release it soon. You can activate the feature by selecting the new option "Hide item count in menubar items" from the "Display" section in preferences.

https://www.dropbox.com/s/9t38uu72tkri6ld/Trailer-152-rc1.zip?dl=0

Let me know what you think and if you have any suggestions or tweaks.

**Comment by ptsochantaris** [comment]
Hi, build 1.5.2 is live and includes this feature, so I'm going to close this issue for now. Please feel free to open new issues if you have any further suggestions on improving or tweaking this feature.

**Comment by rossgardt** [comment]
Great <3 thanks!
