### ISSUE TITLE
GitHub unauthenticated requests rate LIMIT issues

### ISSUE THREAD

**Issue by yomexzo** [ptsochantaris/trailer#302]
AFAIK, Trailer currently uses github personal access tokens to make requests (unauthenticated) which has a rate limit of 60 requests per hour.

On the other hand, authenticated requests (OAuth) has a limit of 5,000 requests per hour.

[See details here](https://developer.github.com/v3/#rate-limiting)

It would be great if OAuth can be implemented so that rate limit approaching notifications are cease/reduce.

**Comment by ptsochantaris** [comment]
Hi @yomexzo,

Currently Trailer adds your personal access token to the auth header for making authenticated requests. This has the same limit as the OAuth authentication scheme (5000 requests per hour). In the link you provide, it's referred to as the "Basic Authentication" option. Trailer uses this because it's super-simple to both set up and implement.

Trailer syncs data incrementally, and additionally any repeated 304 and cached requests don't count towards that limit either. This means that unless you are syncing a HUGE amount of data that changes very often it will be very rare that you hit this limit. Caveat: You *may* get close to hitting it the first time you sync though, if you sync a lot of repos, or repos with a *lot* of items.

You can track your API usage from the "Servers" view in both the macOS and iOS apps. Again, don't worry too much about an initial sync after a setup taking up a big part of that limit, that's fine. Subsequent syncs will take very little.

Hope this helps give you some insight into the API limit issue. Let me know if I have misunderstood the question though!

**Comment by yomexzo** [comment]
Hi @ptsochantaris,

Thanks for getting back.

I just confirmed Trailer [uses basic authentication](https://github.com/ptsochantaris/trailer/blob/master/Shared/API.swift#L1371).

My refreshing settings has "Refresh items every 80 seconds" and "Refresh repos & teams every 2 hours". Does it mean `request rate` = `number of items per 80 seconds` + `number of repos per 2 hours`  + `number of teams per repo per 2 hours`. Please let me know if that is ambiguous. I am just trying to understand why I hit the limit often.

Thanks

**Comment by ptsochantaris** [comment]
Close - the repo and team requests are negligible, they are a couple of requests to update lists, so I wouldn't factor them in TBH.

The number of API calls made isn't as simple as an equation, as a lot of factors come into play, including options, and whether items have been updated on the server (warranting more calls to updated them) etc. However, in general, things that will load up your API usage are:
- Most importantly: Number of items in your menus
- Syncing statuses for PRs (an extra call, or more in some cases, per item)
- Syncing labels (an extra call per item)
- The frequency of your refreshes

If you are hitting the GitHub limit often, then I'd advise raising your refresh cycle to 120 seconds or more, and setting labels and statuses to be refreshed every 3 or 4 refreshes rather than every time. If all else fails, try reducing the number of items you are watching on your repo list, hide a few repos.

**Comment by yomexzo** [comment]
Okay @ptsochantaris.

Thanks.

I will close this issue and re-open if anything else comes up.

Cheers!
