### ISSUE TITLE
Show PRs I've been requested to review

### ISSUE THREAD

**Issue by byyo** [ptsochantaris/trailer#308]
With the new Review feature for GitHub PRs, I've noticed that if somebody requests my review (as opposed to putting me in the Assigned To field or just tagging me in a comment) Trailer.app doesn't show that PR in the dropdown list. It would be really helpful if 'requested review' showed up in the 'Mentioned' section.

I'm using Trailer 1.5.4

Thanks!

**Comment by ptsochantaris** [comment]
Hi @byyo - Thanks for reporting this. This is a known limitation of the GitHub API at this time, it seems to exclude these comments from the comment API stream and doesn't currently provide production API in order to track these review requests. For more information, you may want to track this issue: https://github.com/ptsochantaris/trailer/issues/295

I agree that this is an important missing feature, and together with reaction support, I'm looking forward to adding it as soon as (production) API is available for reviews. GitHub has been adding this for a while now, but for some reason it's still in "beta". Hopefully it won't be too long until we can see review comment support in Trailer.

**Comment by ptsochantaris** [comment]
Actually, come to think of it, this isn't a duplicate, since the functionality you mention isn't the same at that other issue (even though the answer still stands for now, unfortunately). Let's keep this issue open so once the API is available, I can add this in.

**Comment by ptsochantaris** [comment]
Hi, just wanted to update you that there is ongoing work on this feature now. There are beta builds available here for anyone who feels adventurous: https://github.com/ptsochantaris/trailer/pull/314

<img width="487" alt="screen shot 2017-03-11 at 12 36 19" src="https://cloud.githubusercontent.com/assets/521581/23823290/608d7f2e-0657-11e7-9363-00d3bd667160.png">

**Comment by mcgaffin** [comment]
You might have already found this API, but I was looking for this feature from the new Reviews API and couldn't find it. I emailed GitHub support about it. They suggested:

> Here's how you could use the Search API to fetch all review request that you have received:
> ```
> curl -v -H "Authorization: token TOKEN" https://api.github.com/search/issues?q=is:open+is:pr+review-requested:mcgaffin
> ```
> Here's the functional equivalent on github.com: https://github.com/pulls/review-requested

**Comment by ptsochantaris** [comment]
Hi @mcgaffin and thanks for the API suggestion. I haven't considered the search API at all for querying certain types of items during a sync, so this is definitely useful knowledge for the future!

However, for review assignments specifically, this calling pattern would be extra work, as the betas in the linked PR above already query the `requested_reviewers` API endpoint for each PR. This lets Trailer keep a list of requested reviewers, and then it can match them to the latest reviewer status, like approved, requesting changes, etc. (The bit where they list pending reviews isn't quite there yet, it will be a little later on tonight :))

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this issue as v1.5.6 is up now and includes this feature.

Please feel free to open issues related to Review support, bugs, new behaviour or logic that you'd like to see related to support for reviews if you get a chance to try this feature out.
