### ISSUE TITLE
Dashed line under scrollbar

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#309]
Not sure if this is supposed to work like this, but when I scroll issue/pr list I see dashed line as background to the scrollbar:

![2017-02-23_1709](https://cloud.githubusercontent.com/assets/1277526/23265836/a4767490-f9ee-11e6-82ec-402ae9a4bf7b.png)

Actually each dash represents a separator between issue and next issue.

I don't see same dashed line in other windows that have scrollbar in them.

**Comment by ptsochantaris** [comment]
Hi, yes this is a minor display glitch that's needed to be fixed for a while. Thanks for the nudge!

The dashes you are seeing are basically the result of weird compositing artefacts from the translucency effects. For some reason the labels in the displayed cells cause the scrollbar to darken when it passes over them.

I'll take a look at this very soon 👍

**Comment by ptsochantaris** [comment]
Just to let you know I haven't forgotten about this - seems like it's almost impossible to fix, I'm stumped. Will keep picking at it, though. I wonder if it will be eventually fixed as part of a macOS update instead :) (not in High Sierra though - that's still there)

**Comment by ptsochantaris** [comment]
Ok, so, to be fair, following up from my previous comment, macOS was doing its job fine in this case, I'm just bad at understanding the concept of composited vibrancy effects :)

This issue should now be fixed in the codebase and will be in the upcoming 1.6.1 update, but here's a build with this correction in the meantime:
[Trailer.zip](https://github.com/ptsochantaris/trailer/files/1339185/Trailer.zip)

Let me know if it fixes the issue for you, and thanks for all your patience!

**Comment by aik099** [comment]
Confirming, that attached file solves the problem.

**Comment by ptsochantaris** [comment]
Awesome, thanks for testing it!

[Version 1.6.2](https://github.com/ptsochantaris/trailer/releases/tag/1.6.2) is now up and includes these updates amongst other things. I'm going to close this issue for now but please feel free to create further issues if you spot other problems or have more suggestions!
