### ISSUE TITLE
no permanent link for latest version of trailer

### ISSUE THREAD

**Issue by akalman** [ptsochantaris/trailer#319]
so we use boxen to manage our dev environments, and a while back I wrote [a puppet module for trailer](https://github.com/akalman/puppet-trailer).  Its very basic and was just there to get it in boxen.

I'm trying to circle back and add some usability updates to it, and one of the main issues is that I'd like to be able to specify the "latest" version by default.  Unfortunately I haven't been able to find a link that isn't version specific to download from, and I'd like to avoid scraping the github releases page to grab the info.

Is there a link that always points to the latest version of trailer for download, and if not would it be possible to add one?

**Comment by ptsochantaris** [comment]
Hi @akalman - Unfortunately there isn't one right now. I'd love to set up a symbolic link for you to use, but unfortunately the files are being hosted on GH pages, so they get committed by git, and not (S)FTP.  The paths for these releases (linked to from the "official" Trailer page, are http://ptsochantaris.github.io/trailer/trailerXXX.zip, e.g. latest is http://ptsochantaris.github.io/trailer/trailer155.zip)

Like you say, there IS the "releases" page, but scraping it may be a bit hacky. However there is also the appcast XML feed which the Sparkle updater in Trailer uses to check for updates, perhaps that feed may be much easier for you to access (and parse, since it's simple XML) The feed is here: http://ptsochantaris.github.io/trailer/appcast.xml

You only need to check the first entry, since it's always the latest. Tip: Check the BUILD number, not the version number, as in rare occasions I've "snuck in" hotfixes shortly after posting a version :)

Here's the current first entry:
```
<item>
	<title>Version 1.5.5</title>
	<sparkle:minimumSystemVersion>10.10.0</sparkle:minimumSystemVersion>
	<description><![CDATA[<font face="sans-serif" size="3"><ul>
		<li>New option to mark PRs with a badge (and even wake snoozing items up) if new commits have occurred.</li>
		<li>Correction to default visibility settings applied when a custom repository is added.</li>
		<li>Further performance and stability improvements under the hood.</li>
		</ul></font>]]></description>
	<pubDate>Wed, 1 Feb 2017 20:00:00 +0000</pubDate>
	<enclosure
		url="http://ptsochantaris.github.io/trailer/trailer155.zip"
		sparkle:version="1406"
		sparkle:shortVersionString="1.5.5"
		sparkle:dsaSignature="MCwCFH3xqbBnnYwnt5SzFYGRrtiVZTcwAhRa0TxngE2Vz3TpK+vmQY4/f5ZJjA=="
		type="application/octet-stream"/>
</item>
```

So in pseudocode you'd need to hit this file and check the `Channel-> Items[0] -> Enclosure(sparkle:version)` for the latest build number.

I hope this info is of some help. I'll look into perhaps including a "latest.zip" in the path of the files in the future, but (to be embarrassingly honest) I'm worried about forgetting to update one of the two files during a release :)

**Comment by akalman** [comment]
hey so I've finally circled back around to this.

Shame that github pages doesn't support this directly, it seems like something that would be largely used.  In either case the xml file does hit my needs (way better than parsing github.com that's for sure).

I went ahead and wrote the logic against the appcast.xml and it seems to work.  the code that looks up the version looks like this `xmldoc.xpath('/rss/channel/item[1]/enclosure').attribute('shortVersionString')` (using nokogiri, attribute prefixes are pre-parsed out).

this will work under the following assumptions

1. the appcast url doesn't change
2. the path to the desired xml node doesn't change
3. the contents of that attribute are the correct version number in a XX.XX.XX format

from what you've said above, I believe those assumptions will hold so I should be good to go.

**Comment by ptsochantaris** [comment]
Hi @akalman - Nice! I'm glad you were able to parse that file and get that working. Sorry I couldn't provide an easier way - GH pages are a bit limited that way.

About your questions:
1. Yes, there is no scenario in which I can imagine that URL changing, unless the project moved or something drastic like that happened, but even then I bet I'd still have to keep the XML file in this legacy spot for backwards compatibility anyway. Definitely safe to assume that will the XML file be at this URL for a long long time :)
2. I don't believe the path will change, ever. The appcast format has been there for a long while, and Sparkle is a very mature and reliable update framework because it doesn't play fast and loose with things like that. I would imagine perhaps in the future new fields may be added, but I doubt the path would change. Basically as unlikely as (1) above IMHO.
3. Yes, I tend to release even `.0` releases like this, with 3 segments, just to be explicit, BUT I would advise you to check the *build* number instead of the version number, since on some occasions there are subsequent releases using the same version number (usually in cases where a quick hotfix needs to be applied just after a release) So for instance, on the latest `1.5.5` release, the number you probably want is `1406`, as there could theoretically be another `1.5.5` release with an incremented build number, and your parsing would miss it. The build number will always be a single integer, so it's probably even easier to parse, and it always increments, so the higher the number, the newer the build.

Hope this info is useful!

**Comment by akalman** [comment]
If there are two versions of the same release number, would they both appear in the appcast?  If not then I think I'm fine.  If there are two then I'd still be fine if the newer version was first.  Otherwise i'll need to make the build number parsing a bit more complex.

I am now using the build number for checking if the installed version matches the desired version, but I'll be using the short version string also for some other things.

**Comment by ptsochantaris** [comment]
Usually (actually, I think always) hot fixes just replace existing entries, i.e. there is only one entry for 1.5.5 even if there was a new release that incremented its build number for some reason. And yes, the latest version is always at the top - entries are sorted reverse-chronologically, so you should be fine.

Feel free to use either field for displays, both will always be there 👍 Sparkle for instance tends to display versioning as "Trailer 1.x.x (yyyy)". When a hotfix update is published it tends to say "A new build is available (1234) - you have 1.x.x build 1233" ...or something like that :)

**Comment by ptsochantaris** [comment]
Hi @akalman - I'm going to close this issue for now, but feel free to reopen or create a new one if I can be of any more help.
