### ISSUE TITLE
Menu bar counter includes muted items.

### ISSUE THREAD

**Issue by hellopablo** [ptsochantaris/trailer#325]
I have perhaps misunderstood the purpose of muting (new user!), but I'd have assumed that the count in the menu bar would not include muted items? Is this a configuration I've missed? Some PR's I'm tagged in, but not necessarily actively participating in.

**Comment by ptsochantaris** [comment]
Hi @hellopablo and welcome to Trailer!

This isn't a bug per se, it sounds more like you'd be happier using the *Snooze* feature rather than the *Mute* feature.

*Mute* just means that Trailer will not provide you with notifications about an item - there is no other change in how it handles the item, whether that be counting it, checking for other properties, updating its data, etc.

*Snooze* moves an item out of your list, and into a "Snoozed" section. This section can also be hidden by turning on the appropriate option in preferences (i.e. hiding that item, meaning it also goes away from your count)

Snoozed items can be brought back after a certain time or if there are events, it depends how you configure the preset that snoozes the item (e.g. you can have a preset to snooze an item for a certain time and not monitor for events, or you can have another to snooze forever but wake it up if a comment is added, etc) Additionally, of course, you can make the snoozed section visible and just right-click to un-snooze an item manually.

Snoozed items are _also_ muted, so snoozing an item is a super-set of the mute feature in many ways.

It sounds to me like you'd probably want to snooze these items with a "snooze forever and never wake it up" sort of preset, then hide the snoozing section on top of that :)

I hope this helps a bit!

I hope I've understood your question, feel free to keep posting questions though, some of the features are not super-obvious, I must admit.

**Comment by hellopablo** [comment]
Thanks for the detailed response @ptsochantaris!

I think snoozing is exactly what I'm after - took a bit of hunting around to hide the count, but I got there in the end!
