### ISSUE TITLE
Feature Request: Open all PRs/Issues

### ISSUE THREAD

**Issue by hellopablo** [ptsochantaris/trailer#327]
Would be great to have a one-click option to open an entire section in new tabs in the default browser. I often have 5 or 6 PRs to review and just like to open them all in tabs and close them as I review them.

Could be similar in style to the "Remove" button.

**Comment by ptsochantaris** [comment]
Hi @hellopablo - There's no explicit option to do this, but since you just want to open a few PRs immediately, try alt-clicking sequentially on each item. Alt-clicking opens an item in the background and keeps the Trailer menu open for you to select more items. This ought to pretty much do what you need.

**Comment by hellopablo** [comment]
That's perfect, I tried every key apart from alt 🙈

**Comment by ptsochantaris** [comment]
When in macOS, always Alt-click on things, you never know what surprises you're gonna get :) Glad it's helped!
