### ISSUE TITLE
how to hide PR (ou Issues) button in menubar

### ISSUE THREAD

**Issue by bisonfute** [ptsochantaris/trailer#332]
Hi all,
@ptsochantaris thanks for your fantastic product.

I am only interested in Issues tracking/management, that's why I would be very happy to be able to hide the PR button in the menu bar as I am not at all interested in it.

I didn't find a way to do that. Is it something possible ?

thanks !

**Comment by ptsochantaris** [comment]
Hi @bisonfute - I'm glad you're finding Trailer useful.

You can easily achieve what you want by setting the PR visibility options for your repositories to "hidden". To do this, open Preferences and select the "Repositories" tab.

Usually you can select each repo and set visibility to "hide" in the "Pull Requests" column, but if you're not interested in PRs from any repo then you can simply use the "Set all PRs..." button near the bottom to hide PRs for all repos in one go. That ought to do it, and should make syncing a little faster too, since Trailer will not have to check for PRs.

(Also note that you can split repos into their own (or shared) menubar buttons by adding names for them in the "group" column if you wish. Trailer will then "bunch up" items from these repos.)

I hope this helps! I hope I've understood your question correctly, let me know how it goes.

**Comment by bisonfute** [comment]
Wo, what a great answer.
Thanks all of your tips worked and were useful !
The PRs have disappeared and I've grouped issues by topic.
![image](https://user-images.githubusercontent.com/11193622/29840376-185658d4-8d02-11e7-83f2-0d3704c835bb.png)

Thanks for your help.
