### ISSUE TITLE
Add entire org (+ any future new repos)

### ISSUE THREAD

**Issue by JeanMertz** [ptsochantaris/trailer#333]
It would be nice if I could add an entire org to Trailer, instead of individual repos. This would allow me to monitor all org activities.

**Comment by ptsochantaris** [comment]
Hi @JeanMertz and sorry for the slow reply.

In general, Trailer will list items from any repos that are on your watchlist as part of the quick-start and will also auto-add repositories added there (or removed) as time goes on. Trailer doesn't really understand the concept of Orgs as an organisational unit, and I'm wary of adding extra options currently as the app is getting a bit top-heavy with option bloat. However:

By "adding a whole org" do you mean basically adding all the repositories in that org to your local repository list? If so, I could see that being done in a way that doesn't add clutter to the UI: I can expand the "add a custom repository" window so that you can, for instance, specify "*" for the repo name, meaning "all repos from this org". The Trailer would proceed to do that after you click "Add". It would look like:

<img width="609" alt="screen shot 2017-09-17 at 14 54 22" src="https://user-images.githubusercontent.com/521581/30521487-2d548eb2-9bb8-11e7-80d6-f01173a09048.png">

What do you think of this as a solution? Does it fit in with what you had in mind?

**Comment by JeanMertz** [comment]
Thank you for the reply @ptsochantaris, and for creating this great utility.

Your suggestion would definitely be a solution to my problem, yes.

**Comment by ptsochantaris** [comment]
Great, will look into adding that in, then. Adding it to the TODO list.

**Comment by ptsochantaris** [comment]
Hi - just a note to let you know this issue is still on the TODO list, but a [Version 1.6.2](https://github.com/ptsochantaris/trailer/releases/tag/1.6.2) release was needed in the interim since it solves some important display issues in general, and in High Sierra specifically. I've moved the milestone to reflect this. Hope to get started on this soon.

**Comment by JeanMertz** [comment]
Awesome, thanks for the update 👍

**Comment by ptsochantaris** [comment]
Hi again, sorry for the ridiculous wait on this. In my defence all I can say is that this has been a crazy year, and I don't say that lightly :)

This test build should have a testable version of this feature. When you have some time, can you give it a go and see if it works as expected?

[Trailer-168-3.zip](https://github.com/ptsochantaris/trailer/files/2154462/Trailer-168-3.zip)
