### ISSUE TITLE
Styling: Dropdown needs rounded corners at the bottom.

### ISSUE THREAD

**Issue by MichMich** [ptsochantaris/trailer#336]
First of all: awesome work on this app! Very handy.

If you allow me to be a bit of a nitpick: every dropdown shown by a menu-bar item has rounded corners at the bottom of the dropdown. The trailer app dropdown has square corners, which looks like the dropdown is cut-off. It would be great if you could add rounded corners to the dropdown.

Timemachine dropdown: 
<img width="329" alt="screen shot 2017-10-16 at 14 10 35" src="https://user-images.githubusercontent.com/210954/31611298-d2dcfa16-b27b-11e7-8e62-481b936a0316.png">

Trailer dropdown:
<img width="578" alt="screen shot 2017-10-16 at 14 09 28" src="https://user-images.githubusercontent.com/210954/31611256-ae10afca-b27b-11e7-8efb-7bd3e2d27d87.png">

Keep up the good work!

**Comment by ptsochantaris** [comment]
Hi @MichMich,

Thanks for pointing this out!

You know, in all this time, I hadn't noticed this 🤣 

You're absolutely right, of course. I'll look a bit into the windowing API to see how I can make this happen (as Trailer is in fact a window and not a drop-down in a technical sense, even though it pretends to be one). If it's at all possible, I'll be sure to do it.

**Comment by MichMich** [comment]
No worries ... it's not a big issue, so whenever you have time. Whenever you're working on the issue, you might want to adjust the background color to match the native color. It's slightly off.

Again, thanks for the great work!

**Comment by ptsochantaris** [comment]
Hi! Version 1.6.3 is now up and will show nicer rounder corners on the bottom edges of the window, as long as you're on macOS 10.13 - since the API required to do this (without deeper hacks) is only available there.

I definitely read your comment on the background colour, but I would worry about readability in Trailer in dark mode if the background became lighter, keeping in mind that it lists a lot of text, some of it small, compared to a standard menu entry for example. Very happy to talk more about it if you feel that's not a big consideration though.

(PS in a sense I could argue that it _does_ use a standard colour, but it is the colour of the menu bar, and not the menu that shows up as in your Time Machine example :))

**Comment by MichMich** [comment]
Nice work! Much better. Thanks for the quick update! :)
