### ISSUE TITLE
Switch from GitHub's REST API to GraphQL API

### ISSUE THREAD

**Issue by timrs2998** [ptsochantaris/trailer#340]
Trailer has to poll GitHub every so often for a ton of data. It has to make multiple requests to scrape repos, pull requests, issues, and so on (underfetching). Most of the data it gets back is likely unused as well (overfetching). Switching Trailer from REST to GraphQL will solve the overfetching and underfetching issues mentioned above.

I only bring this up because our GitHub Enterprise is being hammered by Trailer users who don't change the default polling interval. Switching to GraphQL would be both beneficial for Trailer's users and those managing GitHub Enterprise instances.

**Comment by kamranayub** [comment]
Yes, please, I really love this thing. 🥇

**Comment by ptsochantaris** [comment]
Hi @timrs2998 

I've wanted to adopt GraphQL for a while now. In fact [the command-line version of Trailer](https://github.com/ptsochantaris/trailer-cli) uses GraphQL exclusively to fetch its data.

That project was partly inspired by the desire to become more acquainted with the v4 API and see how/where it would improve desktop Trailer to move to v4, and also where it could potentially be a problem. Based on that, I can report that there are some "blockers" for GraphQL adoption on the desktop version of Trailer:

The first is knowing if GE servers support this in a widespread manner yet. I wouldn't want to update Trailer to use GraphQL queries and leave existing users out in the cold. Having an option to switch between both APIs for backwards compatibility would just turn the codebase into a mess - since GraphQL data is marked with a different ID scheme, so data would have to be migrated from the old IDs, refetched, etc. to ensure a smooth user experience. This isn't a long-term problem, just more of an argument to "go slow" with adoption. However, this is the least important one.

The most important one is that the GraphQL API makes it impossible to actually sync data incrementally the way Trailer currently does. With GraphQL, data can only be re-fretched whole. Some query types support "if updated since" predicates, but only a subset, and out of those, in ways that aren't really helping (updated_at dates are not touched by many operations, such as reacting or reviewing). This means that Trailer could only realistically use GraphQL only for cases where it re-scans whole data sets anyway: In this case it would be CI statuses and Reactions.

Everything else is incrementally synced, and Trailer makes very few calls to actually update the main data (after the initial sync to populate the local data store, of course). Trailer checks the event endpoint, "dirties" repos and items which have events there, and only polls for the relevant data.

With the GraphQL endpoint it would mean that Trailer would re-fetch all the data each time - which would be a shocking overfetch, and quickly bring down the server if it repeated this every few minutes. In fact, in `trailer-cli`, querying the server more than once every few minutes or so ends up quickly causing a temporary rate ban from the API endpoint, and that is understandable since those queries mean basically doing what is the equivalent of the initial Trailer sync each time, CPU-wise, if not HTTP-wise.

I have repeatedly mentioned to Github that their API would greatly benefit from some sort of timestamped event log, where Trailer and similar apps can check for events and fetch only the relevant data, and they did listen and respond very politely, but my impression is that it's not any kind of priority on their end. They suggested Webhooks which won't work, even if Trailer used some sort of proxy service on the Internet to receive or buffer them, because only admins can add web hooks to repos, so Trailer can't realistically use web hooks to built its own event-logging service which the client could then access.

In the meantime, as mentioned, Trailer uses the v3 repo-event timeline to do something similar and it works quite well, keeping API queries to a minimum and fetching only things that have potentially changed, where it can. However, CI statuses and other API are not supported by the event timeline. The means some items need to be constantly polled-for, which is mostly likely the source of the high traffic that you're seeing.

My initial thought there had been that, GE rate of adoption of API v4 aside, Trailer could still start using the GraphQL endpoint for querying things like CI statuses and reactions, which is far more efficiently done over GraphQL (I don't know about the server load though) but then the API docs point out that the bridging between v3 item IDs and v4 item IDs will be deprecated soon. This means that an app can only use v4 or v3 API in its entirety and not mix things up, because there would be no way to long-term reference between items across API stacks, cutting off the avenue of "hybrid querying" to coin a phrase, or at worst, breaking Trailer at some arbitrary future time if I were to rely on the deprecated ID fields.

So summing up:
- Querying cannot be hybrid v3/v4, app must be either "in" or "out" of v4 because of the ID issue.
- GraphQL does not support incremental sync. It's a full polling of everything or nothing because of the lack of an event log or way to query what has changed after a certain timestamp, or somehow "subscribe" to a query and receive updates based on it. Webhooks can't be installed by a non-admin, so that won't work as event notification.
- Full sync over GraphQL at a sustained rate causes an API rate ban (and if it didn't it would probably end up overwhelming whatever server didn't have one, as it's basically repeated full syncs)

So at this point I'm at a park-and-observe mode. If there was a way to reliably track changes since a date on the API (i.e. fetch the IDs of everything that can be re-queried over GraphQL) then the issue would be solved, as Trailer could then create a targeted GraphQL query which would only fetch changes - the same way it does now on the v3 API (well, at least for most types that the event endpoints log)

I'm sure I'm not the first developer who has encountered this issue - I'm hoping something will show up in the API to help break this dilemma. I'm definitely open to suggestions on how best to tackle this issue, and hope I haven't missed anything important in the API which could perhaps help improve the situation.

Also, I would very much like to discuss this further and see how we can improve the "hammering" you're seeing - perhaps instead of switching to a new API we can look at what queries are the ones that are causing the pain and see if Trailer can be smarter about making them? Let's keep this thread going.

**Comment by ptsochantaris** [comment]
_Narrator: a few years pass, and then..._

First off, happy 2020!

I think I managed to find the best middle ground for heavily leveraging v4 API without having to re-sync everything each time, and have added the option to use v4 API in the new beta available here: https://github.com/ptsochantaris/trailer/pull/400

If you're still interested please do give it a go and let me know how things go in that thread!
