### ISSUE TITLE
Add opened PRs for non-watched repos

### ISSUE THREAD

**Issue by Luzifer** [ptsochantaris/trailer#344]
> As someone often contributing to repositories of other coders I want to be able to track my opened PRs in Trailer.

Lets say I'm watching `Luzifer/.*` repos and now I contribute to `othermaint/project` opening a PR in my fork. What happens is this:

- A new fork was created at `Luzifer/project`
- Trailer detects my watch on `Luzifer/project`
- As `othermaint/project` is a quite popular repo it has many issues and PRs so I don't want to track all of them (too much noise)

As the PR is not targeted at my own repo it is not detected though I want to track it without hiding every single issue / PR on the upstream repo manually. That's why watching that one is no option.

What I want to happen:

- Trailer detects a PR to a repo not being watched by me
- As I set the option "Track PRs created by me" the PR is added to my PR column in Trailer
- I get the usual updates as for PRs against my own repos
  
(Same could apply to issues - like this one - created at popular repos I do not want to watch fully…)

**Comment by ptsochantaris** [comment]
Hi @Luzifer and thanks for the suggestion. Apologies for the rather late reply, winter is always a very busy time work-wise.

What you're saying definitely sounds useful - i.e. being able to track items relevant to you independently of which Repo they come from, but I'm not sure I can see how this could be done via the GitHub API. How would Trailer get notified about the creation of an item in a repo that's not owned or watched by you without checking all repos in GitHub? (And even if that were somehow possible, how would it determine that this PR or Issue is relevant for you?)

I hope I haven't misunderstood your suggestion though. Let me know if I have - happy to discuss this more. The two things that I would basically want to know is (a) How would Trailer detect the creation of a PR by you in another repo and (b) Apart from being created by you, what other criteria would apply in order to get this PR listed in your local Trailer list?

(TBH I think if we're just talking about items created by you then it may be possible to query for them on the API, but if we're taking about items created by others in repos you're not watching - this may be impossible.)

Let me know your thoughts, and I'll definitely try to get back to you a bit faster this time :)

**Comment by Luzifer** [comment]
Nah, you understood it totally correct: It's about issues / PRs created by me towards other repos… Currently I'm using this search for this but of course this is a pull-method while Trailer doing this would be a push-method:

[`author:Luzifer state:open`](https://github.com/search?l=&o=desc&q=author%3ALuzifer+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)

(Some more parameters for sorting etc in the link, not listed in the code)

**Comment by ptsochantaris** [comment]
Cool, so basically this feature would be something like a switch that enables Trailer to also query items created by you, no matter on which Repo. This makes sense, and I think can most probably be added via the API (at the very least, there is the search query you have just provided for example :))

I'll definitely check this out and get back to you, but as a feature it definitely makes sense and could lead to a lot of noise reduction (i.e. not having to watch other repos just to track your PR)

**Comment by ptsochantaris** [comment]
Hi. just a small update to let you know I am looking into this. The reason it's not as much of a slam-dunk as I thought it would be is that checking for user-authored items in repositories that are not currently "managed" by Trailer means the items will come down and just vanish.

To properly implement this, it needs for items to come down, and then Trailer automatically to query and sync the corresponding repository entries for those items once they do. This doesn't mean that it's not doable, but I felt like I should describe why it's not as simple as it may initially sound, hence why it's taking so long to show up.

However, stay tuned :) this is definitely a useful feature that should be added nonetheless.

**Comment by ptsochantaris** [comment]
Hi @Luzifer it seems I found a relatively straightforward way to implement this - this build is from the latest beta, but with the feature added for now (while I test it out as well) and has two new checkboxes in the "Advanced" section of the repository settings (one for PRs and the other for Issues) If you enable them and refresh, and are using the new V4 API, then items which you have created anywhere on GitHub should show up on your list. If you get a chance to try it out and provide feedback and/or bug reports, they'd be very welcome.

[Trailer-1577.zip](https://github.com/ptsochantaris/trailer/files/4432647/Trailer-1577.zip)

**Comment by ptsochantaris** [comment]
Hi, I've merged this into the current beta, so feel free to try it out if you like, check out #400.
