### ISSUE TITLE
Dismissed reviews are shown as green approvals

### ISSUE THREAD

**Issue by sebflipper** [ptsochantaris/trailer#352]
Trailer version 1.6.7 (1471)
macOS 10.13.3 

```cucumber
Given I have enabled the "Display review statuses for PRs" feature
And I have a pull request with an approval
Then I should see the users GitHub username in green under its title
When the pull request review is dismissed (by a changing commit or manually dismissed)
Then the users GitHub username should be removed from the approvers list
```

Currently the pull request menu item is showing GitHub users that have previously approved the PR, but their approval has been dismissed.

**Comment by ptsochantaris** [comment]
Hi @sebflipper and apologies for the late truly. Thanks for pointing this out, will definitely look into it soon.

**Comment by ptsochantaris** [comment]
Hi, sorry for the rather large delay in looking into this. I've tweaked the code that selects the latest review status and this build should fix the issue you have seen above. I did notice a hiccup though, which implies there may be sync issues which don't push down dismissals in some occasions, but it only happened once, it seems to work well otherwise. Here's a test build which you can try out if you like which includes this change. Let me know how you get on with it and/or if you are still seeing this issue.

[Trailer-168-2.zip](https://github.com/ptsochantaris/trailer/files/2153128/Trailer-168-2.zip)

**Comment by sebflipper** [comment]
Thanks for the update! :+1: I've updated to this version and I'll check if this fixes it for new PRs.

**Comment by ptsochantaris** [comment]
I'll close this for now, but if you see this occurring the in the future feel free to open a new issue request.
