### ISSUE TITLE
PR highlighted when I approve a PR

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#358]
I am finding that PRs are highlighted much more than I care.  For example, if I see that there are unread comments counted on someone else's PR, and I drill to that PR and ultimately approve the PR changes, Trailer then ends up showing the Issue marked with an exclamation point.  I don't know if this is due to the setting "Highlight PRs that have new commits" and it is counting approvals as a commit, or if it's a bug with the Reviews setting which should only be notifying of PRs I created (I have no "...or All" checkboxes checked).

At any rate, I don't think I should ever see any notifications/markings due to something I did to a PR.  It should only be from others' actions on the PR.  I already know what I've done to the PRs.

**Comment by ptsochantaris** [comment]
Hi @cgatesman and sorry for my slow reply. Time has been very limited recently and Trailer has fallen behind a bit. I'm working on catching up :)

The mark you are seeing is indeed from the option "Highlight PRs that have new commits". In order to keep bandwidth and API use low, Trailer checks the SHA of the latest commit to the branch, and something is triggering that. I've seen this happen on my own items as well, and I agree it's not ideal.

I'm going to keep an eye on this and try to figure out if Trailer can find a better way to track the latest commit (perhaps there may be an API field that simply shows the number of commits instead, rather than the SHA of the latest commit, for example).

I'll keep this issue open and try to update you along the way.

**Comment by cgatesman** [comment]
Thanks!  Completely understand other things in life can take higher priority, at times.  I'm glad to hear you haven't abandoned us, though.  You have created a great tool for us! 🍻

**Comment by pvinis** [comment]
That is true. In general things that are from our own actions should not be considered updates I guess. When I make a commit to a PR or when I comment, I also get the PR highlighted, but I shouldn't because I made the changes, I already know about them! :D

Also, thank you so much! Trailer is amazing.

**Comment by ptsochantaris** [comment]
For the record, I'm still keeping an eye on this. Trailer has been really low on the priority list this list year, but. I've started taking a look at some easy wins recently. I may get around to this soon - PRs related to this are always welcome, of course!

**Comment by ptsochantaris** [comment]
Hi, I've been looking into this and making some tweaks to the "new commit" detection logic. Can you try this build and see if it improves the issue with highlighting new commits?

[Trailer-1506.zip](https://github.com/ptsochantaris/trailer/files/3748478/Trailer-1506.zip)

@pvinis About your request - Trailer should not notify you or include your own comments in the unread badge, if you're seeing this it may be a bug. But first be sure that you are using an API token for the same account from which you are creating those comments.

**Comment by pvinis** [comment]
I'm back in 2 days, I'll test it out and I might also try to make a PR, or at least give more details.

**Comment by cgatesman** [comment]
This seems to be working for me! 👍
