### ISSUE TITLE
Status filters not working properly

### ISSUE THREAD

**Issue by dgmora** [ptsochantaris/trailer#365]
Hi, first of all thanks for the awesome app!

I was trying to filter the status check to show only steps that failed or running. Say I have these two statuses:

<img width="368" alt="screen shot 2018-08-17 at 09 41 10" src="https://user-images.githubusercontent.com/3609616/44254008-c21abf80-a201-11e8-8432-649d5dea04cd.png">

With these settings:

<img width="532" alt="screen shot 2018-08-17 at 09 42 22" src="https://user-images.githubusercontent.com/3609616/44254039-e24a7e80-a201-11e8-8f04-4c27d4915cc7.png">

The appearing status seem to change to:
<img width="360" alt="screen shot 2018-08-17 at 09 42 13" src="https://user-images.githubusercontent.com/3609616/44254041-e37bab80-a201-11e8-9682-5eb65851621e.png">

So the build step shows as running when it's not. I'm not sure if it's a problem with tariler or the API returning too many statuses.

Version: 1.6.8

**Comment by ptsochantaris** [comment]
Hi @dgmora and thanks for reporting this. I think I see the problem you're reporting - basically, if I understand correctly, the statuses that are being filtered, even though they contain the string you have provided, shouldn't appear because they are past statuses and not current statuses of the PR, have I got it right?

**Comment by dgmora** [comment]
Hi @ptsochantaris, I think that's probably the cause, yes 🙂

**Comment by kamilpp** [comment]
Hey, we see this issue still occurring (1.6.16). This is really useful feature so would be awesome to have it working right 👍

**Comment by ptsochantaris** [comment]
Hi, and thanks for the bump. I haven't been able to look into any Trailer issues at all recently because of an overwhelming amount of work. All these are definitely in the TODO list and I'm hoping to get to them soon once I have a little more free time. (Worth noting that, in the meantime, PRs and suggestions are of course more than welcome!)

**Comment by ptsochantaris** [comment]
Hi and sorry for taking more than half a year to get around to this (#facepalm). I finally found a little time to do some Trailer work! I think I may have fixed this issue, but could you give a go to this build and see if I have correctly understood/fixed the problem?

[trailer1489-test.zip](https://github.com/ptsochantaris/trailer/files/3144374/trailer1489-test.zip)

**Comment by kamilpp** [comment]
@ptsochantaris it works for me, awesome, thanks! :)

**Comment by ptsochantaris** [comment]
Excellent news, thanks for testing it out!
