### ISSUE TITLE
1.6.9 using a lot more GitHub API volume

### ISSUE THREAD

**Issue by jaredreynolds** [ptsochantaris/trailer#368]
I upgraded from 1.6.8 to 1.6.9 when prompted and now Trailer keeps notifying every hour about approaching the GitHub API usage limit. Admittedly, I watch a large number of repos but 1.6.8 didn't seem to have this problem. I changed my refresh rate from 120 to 240 but am still getting the warning--possibly indicating at least 2x more volume. My coworkers who recently upgraded are also reporting this problem.

Platform:  Mac OS 10.13.6
Trailer version: 1.6.9

**Comment by ptsochantaris** [comment]
Hi @jaredreynolds - thanks for reporting this. 1.6.9 does indeed have some changes on the networking side which could be related. Basically, it got rid of code in 1.6.8 which was basically a local caching layer, and now relies on the macOS/iOS system caching for HTTP calls. The reason is partly that the code was a bit flakey, complicated to maintain and debug, and that it seemed to totally break in certain circumstances in Mojave as well. I did test 1.6.9 using a proxy and it did seem as if the system was doing the right thing, taking advantage of Etags and handling 304 responses properly - which makes what you're seeing quite interesting.

What would cause your API usage to increase is if there were calls that were resulting in 20x codes rather than 304s because of some changes in how caching differs between 1.6.8 and 1.6.9. Is there any chance you can temporarily run a proxy on Trailer to see what kind of response codes are coming back? I'd normally say "enable Log activity to console" and watch the console, but in this case 304s will be "masked" as 200s by the system cache.

Another thought is, what if you are following so many repos that a refresh has just too much stuff for the system cache on its default settings, and the cache ends up evicting stuff you need in the next refresh? Let me know on the amount of 304s vs 200s that you get as API result codes, and perhaps we can try a build with a much larger custom cache to see if it improves things for you.

**Comment by jaredreynolds** [comment]
Thank you for the very quick response and fix!  I'm testing the new version now and it looks great!  As mentioned, the first pull to populate the cache used a lot but now it's using practically nothing.  👏
