### ISSUE TITLE
"Approved by me" status not showing

### ISSUE THREAD

**Issue by pnarielwala-tc** [ptsochantaris/trailer#370]
Hello!

First of all, this is an amazing app! Improved my productivity greatly and I've been able to see and review other's pull request more quickly!

I've noticed that a feature that had worked before seems to not work fully anymore: When I approve someone's pull request, I used to get `@pnarielwala-tc approved changes`. Now they don't appear anymore even though I _do_ see if other people approve pull requests (in green). I miss that since it gave me some gratification that I finished reviewing those PRs 🙂 

I hope this description was helpful and can be fixed. Thanks again for this incredible app!

Parth

**Comment by ptsochantaris** [comment]
Hi @pnarielwala-tc and thank you so much for your kind words, I'm really happy you're finding Trailer useful!

What you mention is interesting - looking at my "test" PRs in my test repo, I have a feeling that you're right. This may be an API change from Github I need to catch-up with, or a straight-out regression from my end.

Thank you for letting me know, I'll look into it soon. I definitely agree that you should see "X approved/requests changes" like you say, at the very least it's a useful guide. I'll keep you posted with what I find out 👍

**Comment by pnarielwala-tc** [comment]
Awesome, thank you!

**Comment by ptsochantaris** [comment]
Hi, so just a quick update - I did have a look at the PR I mentioned yesterday, but it turns out Trailer was doing the right thing, as my approval down the line had been dismissed by my test user, so Trailer was hiding that approval correctly. Re-approving that test PR seemed to do the right thing, i.e. it's showing as `@ptsochantaris approved changes` for example.

It's interesting that you're not seeing this - is this on a public PR by any chance so I can try to replicate your specific issue?

**Comment by pnarielwala-tc** [comment]
Hello! So it seems like it's working now! Maybe something github fixed on their end? I'll mark this closed, thanks for looking into this!
