### ISSUE TITLE
How does Trailer fetch everything that's updated?

### ISSUE THREAD

**Issue by oliverzheng** [ptsochantaris/trailer#390]
I'm trying to understand the sync behavior of Trailer. It seems like PRs created before the first sync but updated after are not pulled in. I cracked open the sqlitedb and saw that there's 100 PRs for a repo I'm in, which has at least an order of magnitude more open PRs than that. When I look at the Trailer logs, it seems that it calls the `/pulls` API but does not sort by `updated`, which means it sorts by `created` by default.

This raised some questions in my head:
- It almost seems like Trailer only updates PRs while they are open. If my PR gets a comment after it merges, would Trailer see that?
- Is there some truncation of list of all PRs to 100?
- If I stay offline for a long time (relative to how frequently the repo gets updated), is it possible to miss some PRs?

I tried reading some of the code, but my Swift reading ability is kinder-garden level at best. I'd appreciate any pointers to help my understanding!

**Comment by oliverzheng** [comment]
I'm realizing the proxy I'm running wasn't forwarding HTTP headers, thus not forwarding the `next`/`prev` links. Hence it wasn't getting anything past 100 PRs. 😩 Sorry for the churn.

I'm still curious about the sync policy though!

**Comment by ptsochantaris** [comment]
Hi @oliverzheng and sorry for the extremely slow reply. Things were quite busy and then I managed to miss responding to quite a few issues here. To answer your questions:
- Trailer will normally only query open items. This recently changes on the most recent beta in #400 and you are more than welcome to try it out.
- Glad you located the issue there, let me know if you have any more.
- That's a good question. In theory, yes, because if an item is opened and closed while you were offline, then it will never show up for you, since Trailer will query only items that are open, or items that are already in its list and then closed or merged. It won't automatically show items which are new but closed.

I hope this helps a bit, please accept my apologies for missing your comment here, I promise to keep an eye on the issues a bit more from now on.
