### ISSUE TITLE
Wake key doesn't work?

### ISSUE THREAD

**Issue by zenspider** [ptsochantaris/trailer#391]
I get that I am supposed to use up/down arrows to walk through the list, but cmd-shift-"o" just beeps. I thought maybe I misinterpreted but I've used every combo of cmd/shift/oh/zero to figure it out to no avail. Clue me?

**Comment by zenspider** [comment]
Also, it'd be REALLY nice if I could wake everything currently in the list (like, after doing a search)

**Comment by ptsochantaris** [comment]
You're right, it's not working! Thanks for reporting it, I'll dig into it.

**Comment by ptsochantaris** [comment]
Hi, I think I found the issue - not quite a "bug" in the strictest sense of the word, but basically the shortcut was wrong - it should have been option-command-zero, not shift-command-zero. The idea is that you can hit option-command-[number] to pre-select a snoozing prefix, and "0" is the one that wakes them up. For some reason I had set the shortcut as "shift" which is wrong because (a) You can't do shift-modified shortcuts with number keys without risking not working on various keyboard layouts and (b) as mentioned above, it doesn't fit with the pattern!

Here is an updated RC build that should fix this, let me know if it works for you:

[trailer1617.zip](https://github.com/ptsochantaris/trailer/files/3292961/trailer1617.zip)

BTW your suggestion for a "wake all" option is a good one, I've added it to the TODO list 👍 Hopefully the hotkey fix should improve the experience for you in the meantime.
