### ISSUE TITLE
No notification from closed PR

### ISSUE THREAD

**Issue by azubala** [ptsochantaris/trailer#394]
Environment:
- App Version: 1.6.17 (1497)
- MacOS: 10.15 (19A583)
- standard Github server

It seems like @-mentiones from closed / merged PRs are not coming to the app, while Github e-mail notifications are being sent in such cases. Is there a setting to enable that or it's not supported?

**Comment by ptsochantaris** [comment]
Hi @azubala, sorry for the very slow reply.

Trailer only queries open items, when an item is closed then it's no longer available on the API and it is removed from your list. In theory Trailer could then poll previously closed or merged items individually, but that would basically burn API quota like crazy - currently it only fetches PRs info in batch requests. I hope I understood your question correctly, let me know if you need me to clarify (or if I need some clarification :))

**Comment by azubala** [comment]
@ptsochantaris thanks your response (no need to worry about the delay, you're awesome working on this open source app 💪 )

> when an item is closed then it's no longer available on the API

yup that's pretty much what I imagined. It's a pity since I moved to trailer.app only when it comes to GH notifications but I learned that I missed some comments from my closed PRs. Which means I need to check e-mail notifications as well.

Perhaps we could add something like on-demand check? Or a daily check of those kind of mentions?

**Comment by ptsochantaris** [comment]
One thing we could do, I suppose, is to have an option to periodically check closed PRs, as long as they are still on the list of items (i.e. in the closed or merged section) - however the check would have to be less frequent than the rest of the items, since each PR would have to be queried separately. Would something like that work for you, or is your base-case more about getting comments from long-closed PRs? If so, a user-defined list of checks would probably make more sense, like you suggest.

**Comment by ptsochantaris** [comment]
Hi and wishing you a happy 2020!

There is a new beta available here: https://github.com/ptsochantaris/trailer/pull/400 which contains an option to do this now, which is possible because of big changes on how Trailer now does sync (and hence the need for a beta :)) You're very welcome to try it out and let me know of issues and if the feature works correctly for you.
