### ISSUE TITLE
Some items are hidden by your settings -- but what?

### ISSUE THREAD

**Issue by dcsobral** [ptsochantaris/trailer#401]
I'm rather frustrated at the moment that trailer is showing me that there's 16 items, but they are hidden by my settings, and I can't figure out which items or which settings.

It would be really nice if I could somehow show the stuff that is hidden.

**Comment by ptsochantaris** [comment]
Hi @dcsobral - I realise my reply is super-late, but I haven't been able to think of a good response to this issue :) First off, you're right, Trailer has so many options that not knowing what was hidden by what option must can be very frustrating - that's why usually it's a good idea to try relying less on filtering and more on just syncing what's needed (makes good API sense too). On the other hand, I really can't see any reasonable way where the current code in Trailer could be easily adapted to show what items were hidden by what rule, as basically it would involve changing the some big parts of the core of the app, but one thing which can be added relatively simply is to have a button which accompanies the hiding message, which would reset any visibility preferences back to their default values, so that you can at least "unearth" the "lost data" and not have to worry that you are missing anything important. Does this make some sense / would it be useful? I know it's not quite what you had in mind, but would this be some substitute at least?

**Comment by dcsobral** [comment]
Yes, that would be useful.

**Comment by ptsochantaris** [comment]
Hi, this can also act as a short term workaround: https://github.com/ptsochantaris/trailer/issues/426#issuecomment-841895867

**Comment by ptsochantaris** [comment]
If you'd like to try a preview of this, this build contains an option in Preferences -> Misc that will list all hidden items and the reason each is hidden. Please note that as of version 1.8.8 the app will move your token to the keychain, so if you need to downgrade from this build you'll need to search for "trailer" in the keychain and copy the token back to the previous version from there. Any and all feedback always appreciated!

[Trailer-1701.zip](https://github.com/ptsochantaris/trailer/files/12384425/Trailer-1701.zip)

**Comment by ptsochantaris** [comment]
An update with some fixes

[Trailer-1702.zip](https://github.com/ptsochantaris/trailer/files/12384833/Trailer-1702.zip)

**Comment by ptsochantaris** [comment]
Version 1.8.8 is now up and contains this feature. Will close this issue now, but please feel free to open new issues related to this or other problems/suggestions.
