### ISSUE TITLE
Draft indication not functional in 1.7.x builds

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#408]
Verified on 1561 & 1562, draft PRs are no longer hidden or include "draft" in the title, depending on which preference you have selected.

**Comment by ptsochantaris** [comment]
Hi, thanks for reporting this. I'm seeing this too, no clue why I missed it (and your report!). Digging into it now.

**Comment by ptsochantaris** [comment]
Problem definitely found and fixed. At some point I managed to remove the field that indicates if a PR is a draft from the GraphQL query #facepalm

I've fixed this in the code, and I'll roll this fix out with a build that's about to go out now containing some other fixes as well, so check for an update soon and things should go back to normal. Note: You may have to select "reload all data" from preferences in order to refresh existing items.

Thanks of reporting this and sorry once again for the ridiculously late turnaround time on this.

**Comment by ptsochantaris** [comment]
Hi, I'm closing this issue as the update with the fix is now live, but please feel free to reopen or create a new issue if you spot any more related problems. Thanks again for testing the beta and reporting this, and sorry once again for me managing to miss it for so long!
