### ISSUE TITLE
GitHub v4 Successful Test but no data and red X

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#414]
I'm trying to enable v4 API.  I get a successful Test with it, but there is no data and I have a red X even after restarting the app.  Am I just missing a step for switching over to v4?

<img width="881" alt="Screen Shot 2020-09-22 at 12 21 05 PM" src="https://user-images.githubusercontent.com/6276072/93909764-24422a80-fcce-11ea-979c-c4963aaee411.png">

<img width="514" alt="Screen Shot 2020-09-22 at 12 19 55 PM" src="https://user-images.githubusercontent.com/6276072/93909647-f4932280-fccd-11ea-987f-c31a6928c3d0.png">

**Comment by ptsochantaris** [comment]
Hi, when you switch to the v4 API Trailer needs to re-sync everything, which is why there is no data, but the red X implies the sync has failed. You can get more info on what's going on there by enabling logging from the "Misc" menu, it may give you a sense of where the calls may be failing. More than happy to dig into any logs you think may be relevant. One thing to try perhaps is to only sync a small subset of small repos to see if _that_ works and this isn't some throttling weirdness from GitHub. They _do_ tend to have some broken and inconsistent rate limiting on this API.

**Comment by cgatesman** [comment]
Thanks, @ptsochantaris!  It turned out to be insufficient scope.  Apparently API v4 needs more?  I was able to add the ones the message stated, and everything started working.  Is it documented anywhere what the minimum scopes for Trailer are?

```
2020-09-24 15:30:39.763 Trailer[98360:6292487] (GQL 'GitHub: Reviews, Comments, Requests')  Error: Failed with error: 'Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['gist', 'repo', 'user'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.'
```

**Comment by ptsochantaris** [comment]
Hi @cgatesman - interesting, I never seemed to get that error, but most probably I may have already enabled those permissions! Either that or GitHub changed things around again...

I'll be sure to add this text to the placeholder in the API token field so other people don't encounter this as well. Thanks a lot for getting back to me with this info, much appreciated!
