### ISSUE TITLE
Can't disable comment notifications from codecov

### ISSUE THREAD

**Issue by JustinAiken** [ptsochantaris/trailer#430]
Trying all kinds of formats to block:

![Screen Shot 2021-03-10 at 8 52 09 AM](https://user-images.githubusercontent.com/1568662/110657301-f79ba580-817d-11eb-9238-028758177ba6.png)

But I keep getting on every PR I'm watching:

![Screen Shot 2021-03-10 at 8 51 57 AM](https://user-images.githubusercontent.com/1568662/110657381-06825800-817e-11eb-9bed-8b8cebbd68d4.png)

**Comment by ptsochantaris** [comment]
You don't need to prefix `@` in that list, in fact on macOS it may end up trying to block `@@codecov[bot]` because the code isn't very smart about trimming the `@` :)

Can you try adding a `codecov[bot]` to that list and see if it helps?

If not, there may be some mischief happening with the square brackets which I should look into - let me know now it goes.

**Comment by JustinAiken** [comment]
Added `codecov[bot]` to the list, will post back tomorrow if it works!

**Comment by ptsochantaris** [comment]
Did it help?

**Comment by JustinAiken** [comment]
Oh yes, that did the trick!
