### ISSUE TITLE
Review requests don't seem to work

### ISSUE THREAD

**Issue by charrondev** [ptsochantaris/trailer#445]
Where am I supposed to see these?

|Description|Image|
|---|---|
|My Settings|<img width="623" alt="image" src="https://user-images.githubusercontent.com/1770056/131854315-fa5809d5-3b1e-4ac3-8261-8d272e6ae1b9.png">
|My Review Requests|<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1770056/131854400-9dd74b6d-0812-4328-b469-9ecc8e9bc6ba.png">|
|What I actually see|<img width="542" alt="image" src="https://user-images.githubusercontent.com/1770056/131854469-8c88e4ff-e762-479b-8506-eb571666ae6b.png">

I was expecting to see the "Review Requested" somewhere in here.

**Comment by ptsochantaris** [comment]
Hi! I see from your screenshot that most of the review requests are in PRs from a repo called "vanilla-cloud", which don't seem to be listed in your trailer, so the issue of whether there was a review requested from them or not doesn't apply, since they don't seem to be visible based on whatever criteria you have selected in the first place. So my advice would be to first see why those PRs aren't being listed at all, and most probably once they are, they should move to the section you have configured for review requests.

I hope this makes some sense and that I've understood your issue correctly, but let me know if I'm missing the point!
