### ISSUE TITLE
[BUG] PR Closed / PR Reopened notifications keep popping up for PRs that haven't been closed at all

### ISSUE THREAD

**Issue by JustinAiken** [ptsochantaris/trailer#447]
Trailer 1.76

I keep seeing notifications like this:

![Screen Shot 2021-10-07 at 10 05 53 AM](https://user-images.githubusercontent.com/1568662/136422375-0428d1bd-5674-498d-ba95-615d33f2a8e9.png)

And then about 10 minutes later, a matching "PR Reopened" notification.

But clicking through to the PR on github, it's never been closed or reopened.

Seems to happen sometimes when a commit is added to a PR I'm watching, but sometimes for no reason also ¯\_(ツ)_/¯

**Comment by ptsochantaris** [comment]
Sorry for never replying - I think the issue you're describing happens when you are tracking authored items from repos that aren't enabled otherwise in Trailer. The recent beta should correct this. If you get a chance to have a go and see any difference do let me know: https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!

**Comment by JustinAiken** [comment]
Yep, haven't seen this since updating to 1.8.1, thanks! =)
