### ISSUE TITLE
Whitelisting repositories with filter

### ISSUE THREAD

**Issue by Anonycoders** [ptsochantaris/trailer#462]
Hi,

I'm trying to discover all the features and parts in this amazing application, but one thing that caught my attention so far was **Filtering** and I saw that there are two types of filtering:

1. In the search bar
2. In the filtering section

I'm using Trailer in a big company which has too many labels that I can not include them one by one in feature section.
I was wondering if there is a workaround here so f**or example I put 5 filters in the Filters page and Trailer only displays the PRs/Issues that have at least one of those 5 filters**.

P.S:
I've already tried putting labels like **!label 1, !label 2** and **also -label1, -label2** but didn't work.

**Comment by Jecoms** [comment]
This would be a great addition. I have more use of an allow-list than a block-list.

**Comment by ptsochantaris** [comment]
Hi, sorry for not spotting this a little earlier - on the menus you can exclude multiple labels like this: 

Things are ORed inside a single `label:` prefix, so, e.g.:
`label:!enhancement,!bug` would exclude all items that contain either the `enhancement` or `bug` labels
`label:enhancement,bug` would show only items that have the `enhancement` or `bug` labels

If you want to AND things, you can add multiple `label:` statements, since separate items get ANDed. So for instance:
`label:enhancement label:bug` will only show items that have _both_ the `enhancement` or `bug` labels.

This rule holds for all filtering settings, not just labels. I hope this helps!

**Comment by ptsochantaris** [comment]
Coming back to this issue, it does sound like a great option could be to add a "only show items that..." toggle to the current exclusion lists in the same way we do for statuses:
- Labels
- Item Authors
- Comment authors

Adding this to the TODO list 👍

**Comment by ptsochantaris** [comment]
Hi, this build contains a first version of this feature - each of the exclusion lists now has an dropdown that can change its behaviour to act differently, for example only showing items with specific labels. If you get a chance to try it out and have and feedback or suggestions they'd be very welcome.

<img width="664" alt="Screenshot 2023-08-25 at 10 59 30" src="https://github.com/ptsochantaris/trailer/assets/521581/e25804e9-270c-4e42-859c-e4395c9db90d">

<img width="429" alt="Screenshot 2023-08-25 at 10 59 21" src="https://github.com/ptsochantaris/trailer/assets/521581/e9c9236f-0de1-4558-b931-c809af5a2a29">

[Trailer-1712.zip](https://github.com/ptsochantaris/trailer/files/12437933/Trailer-1712.zip)

**Comment by ptsochantaris** [comment]
Closing this as it has been sent out with the latest update, but please feel free to create issues with feedback and/or more suggestions related to this or other bits! 👍
