### ISSUE TITLE
Filtering PRs opened by a Github app not working

### ISSUE THREAD

**Issue by bob-laz** [ptsochantaris/trailer#466]
Our org has many PRs opened by a Github app, similar to Dependabot. Filtering these items by username does not appear to be working. 

Perhaps this is just be not understanding how filtering works, but I have tried setting up my filtering as follows:

<img width="583" alt="Screen Shot 2022-11-29 at 8 57 10 AM" src="https://user-images.githubusercontent.com/15270286/204578837-5d213086-25f7-4eb5-80de-76b08734ec4e.png">

In PRs listed in the tool, notably I do not see any author or labels:

<img width="468" alt="Screen Shot 2022-11-29 at 8 56 53 AM" src="https://user-images.githubusercontent.com/15270286/204578776-227dc51c-9898-4a51-9ba5-73c6d372de27.png">

Like I do with PRs not opened by the bot:

<img width="444" alt="Screen Shot 2022-11-29 at 8 59 57 AM" src="https://user-images.githubusercontent.com/15270286/204579574-7395dc6a-e441-4f0f-b6ad-6c7b3e118836.png">

Interestingly, if I use the "Reload all data" feature and remove the "security fix" label filter, for some time labels will be populated again and if I add the "security fix" label filter back, I see these PRs getting filtered out correctly. I still do not see any author data though.

<img width="445" alt="Screen Shot 2022-11-29 at 9 00 58 AM" src="https://user-images.githubusercontent.com/15270286/204579994-d3e74eb1-757d-45b5-a41f-b30ac86832f6.png">

However, after some time, label data is missing again and the label filter no longer works. 

Love the tool and let me know if there's any additional information I can provide.

**Comment by ptsochantaris** [comment]
Interesting, thanks for reporting - I'm going to look into https://github.com/ptsochantaris/trailer/issues/455 shortly, and somehow this "feels" like it could be related. In the meantime if you have a simple way to replicate this issue with a public repo that would be extremely helpful for me to track it down.

**Comment by ptsochantaris** [comment]
That’s brilliant, thank you, going to give this a go and try to find out what’s going wrong there.

**Comment by ptsochantaris** [comment]
Hi, can you give version 1.8.1 a try to see if it corrects this issue? The v4 API had a weird design quirk where users and bots were not provided as the same type of data, even though they had identical fields, which meant the authors of comments and items would just say empty. I've updated the logic there to hopefully correct this, and since 1.8.1 needed to go out anyway to correct a bug, I've included it there as a yolo fix :) For what it's worth, if you add `dependabot` into your preferences field it will not filter out the items in your example above. Let me know how it goes!

**Comment by ptsochantaris** [comment]
Ah, that's a good tip, I usually don't use this feature (as you can tell :)) so this is super useful to know. I suspect that the `[bot]` suffix is added by v3 in order to distinguish the user as a bot, whereas in v4 that entry is sent down as a different type. I'll definitely make a note to add this to the info placeholder on the view, thanks!

Sorry for taking positively ages to respond to this (and other) issues - I'm hoping to up my involvement with Trailer a bit more these days :) Thanks so much for reporting and testing out the fix. Going to close this issue now but as always feel free to re-open if needed, or file more issues!
