### ISSUE TITLE
Filter older Recently Merged PRs

### ISSUE THREAD

**Issue by rbos-dhl** [ptsochantaris/trailer#477]
I like the Recently Merged section, but I would like it to automatically remove PRs older than a number of days. I'm familiar with the Snooze option, but, as far as I know, you cannot limit that to one section.

**Comment by ptsochantaris** [comment]
That's a neat idea - especially since in v4 you can still receive notifications on those if you wish. Definitely going on the TODO list. The question is though - do we want to auto-remove items based on the date of their creation or date of last update? I strongly suspect the latter but would definitely value your thoughts on this as well.

**Comment by rbos-dhl** [comment]
Yes, date of last update is definitely the one I would want.

**Comment by ptsochantaris** [comment]
Hi! Here's a build which contains a first version of this feature, which will be in the next release. If you get a chance to try it out and have any feedback it would be more than welcome! Please note that 1.8.8 and up will move your auth tokens to the keychain, of if you need to downgrade you can find your old auth token your keychain by searching for "trailer" and re-enter it into the old version.

[Trailer-1703.zip](https://github.com/ptsochantaris/trailer/files/12385635/Trailer-1703.zip)

**Comment by rbos-dhl** [comment]
Yes, that works well! 👍 

Minor issue in the configuration itself: when I set it to a number of days, e.g., 3 and then close the configuration, and reopen that configuration to change it, the arrows don't work as excepted: down goes to 'Keep...' (rather than 2 days), and up goes to 'Automatically... a day', so it seems like the arrows don't take the current setting into account but just cycle through the options?

**Comment by ptsochantaris** [comment]
Oh indeed, that's my bad, thanks for spotting that, I'll be sure to fix it up 👍 I didn't notice it because I was using "1" to test, just goes to show that until someone apart from the dev uses the app, it's just not really tested :D Thanks for trying it out! I'll be sure to include this in the upcoming release.

**Comment by ptsochantaris** [comment]
Version 1.8.8 is now up and contains this feature. Will close this issue now, but please feel free to open new issues related to this or other problems/suggestions.
