### ISSUE TITLE
I don't see PRs where I'm added as reviewer

### ISSUE THREAD

**Issue by danielebogo** [ptsochantaris/trailer#492]
I don't see PRs in my list where I'm assigned as reviewer, unless I participated doing the review or leaving a message

**Comment by ptsochantaris** [comment]
Hi! Currently there is no promoting logic for being assigned as a reviewer, so for example, would the PRs have appeared in your list even if you were not assigned? You can get the logic behind why some items are hidden from `Misc` -> `Hidden Items` in preferences, it may help us know what is going on there.

**Comment by danielebogo** [comment]
Hi @ptsochantaris thanks for your reply. I checked the hidden items, and I see that PR is marked as `-- Repo setting: Only Mine and Participated sections allowed`. Nobody is assigned to that PR but many are added as reviewers.

I believe that if I assign that PR to myself I'm getting notified, but I'm working on different projects with different approaches.

Is it something that can be added? For example, in Quests I can see all the PRs I'm added as reviewer but not assigned

**Comment by ptsochantaris** [comment]
Thanks for the quick update! Yes, I think it's pretty clear from that log that what's happening is that you have set the repo to only show participated PRs, but, with the current app logic, the PR is not participated in just by virtue of it being assigned for review. What happens if you go to the "Reviews" tab and set a PR to be moved to the Participated section if it has been assigned for review? That should, in theory, promote it to "Participated" and hence show up for that repo, if my memory of the sorting logic is correct 😆 - if not, I should probably take a look at that code.

**Comment by danielebogo** [comment]
> What happens if you go to the "Reviews" tab and set a PR to be moved to the Participated section if it has been assigned for review

🤦‍♂️ there you go! Thanks a lot @ptsochantaris ! This works as I'm expecting it!

**Comment by ptsochantaris** [comment]
🎉 Oh nice! I'm glad that solved it 👍 Feel free to open more issues if you run into problems. I'll close this issue for now, but feel free to re-open in case you have more issues related to this topic too.
